// ==============================================================================
// PrintFlow SaaS - Authoritative Landing Page Default Configuration
// Strictly aligned with Master Implementation Prompt copy and structure rules
// ==============================================================================

import type { LandingPageConfig } from '@/types/landing-page.types'

export const DEFAULT_LANDING_SECTIONS = [
  {
    id: 'hero',
    key: 'hero',
    nameEn: 'Hero',
    nameBn: 'হিরো সেকশন',
    enabled: true,
    order: 1,
  },
  {
    id: 'without_printflow',
    key: 'without_printflow',
    nameEn: 'Without PrintFlow',
    nameBn: 'প্রিন্টফ্লো ছাড়া অবস্থা',
    enabled: true,
    order: 2,
  },
  {
    id: 'with_printflow',
    key: 'with_printflow',
    nameEn: 'With PrintFlow',
    nameBn: 'প্রিন্টফ্লো ব্যবহারের সুবিধা',
    enabled: true,
    order: 3,
  },
  {
    id: 'workflow',
    key: 'workflow',
    nameEn: 'Workflow',
    nameBn: 'মূল কাজের ধাপ',
    enabled: true,
    order: 4,
  },
  {
    id: 'employees',
    key: 'employees',
    nameEn: 'Employees',
    nameBn: 'কর্মী ব্যবস্থাপনা',
    enabled: true,
    order: 5,
  },
  {
    id: 'what_we_manage',
    key: 'what_we_manage',
    nameEn: 'What PrintFlow Manages',
    nameBn: 'যা কিছু পরিচালনা করা যায়',
    enabled: true,
    order: 6,
  },
  {
    id: 'industries',
    key: 'industries',
    nameEn: 'Industries',
    nameBn: 'শিল্প খাত',
    enabled: true,
    order: 7,
  },
  {
    id: 'companies',
    key: 'companies',
    nameEn: 'Registered Companies',
    nameBn: 'নিবন্ধিত প্রতিষ্ঠান',
    enabled: true,
    order: 8,
  },
  {
    id: 'bangladesh',
    key: 'bangladesh',
    nameEn: 'Bangladesh',
    nameBn: 'বাংলাদেশ ফিচার',
    enabled: true,
    order: 9,
  },
  {
    id: 'mobile',
    key: 'mobile',
    nameEn: 'Mobile',
    nameBn: 'মোবাইল ব্যবহার',
    enabled: true,
    order: 10,
  },
  {
    id: 'pricing',
    key: 'pricing',
    nameEn: 'Pricing',
    nameBn: 'মূল্যতালিকা',
    enabled: true,
    order: 11,
  },
  {
    id: 'faq',
    key: 'faq',
    nameEn: 'FAQ',
    nameBn: 'সাধারণ প্রশ্নোত্তর',
    enabled: true,
    order: 12,
  },
  {
    id: 'final_cta',
    key: 'final_cta',
    nameEn: 'Final CTA',
    nameBn: 'চূড়ান্ত আহ্বান',
    enabled: true,
    order: 13,
  },
]

export const DEFAULT_LANDING_FAQ = [
  {
    id: 'faq-1',
    questionEn: 'What is PrintFlow?',
    questionBn: 'প্রিন্টফ্লো কী?',
    answerEn: 'Business management software built specifically for print and signage businesses.',
    answerBn: 'প্রিন্ট এবং সাইনেজ ব্যবসার সব কাজ এক সাথে পরিচালনা করার আধুনিক সফটওয়্যার।',
    enabled: true,
    order: 1,
  },
  {
    id: 'faq-2',
    questionEn: 'Who is PrintFlow for?',
    questionBn: 'প্রিন্টফ্লো কাদের জন্য উপযোগী?',
    answerEn: 'Digital print shops, offset presses, flex & banner makers, acrylic/LED fabricators, and installation teams.',
    answerBn: 'ডিজিটাল প্রিন্ট, অফসেট প্রেস, ফ্লেক্স-ব্যানার ও সাইনেজ তৈরির সব ধরনের প্রতিষ্ঠানের জন্য।',
    enabled: true,
    order: 2,
  },
  {
    id: 'faq-3',
    questionEn: 'Can I manage production and inventory?',
    questionBn: 'প্রোডাকশন এবং ইনভেন্টরি কি একসাথে নিয়ন্ত্রণ করা সম্ভব?',
    answerEn: 'Yes. Every job order automatically tracks media rolls, sheet stock, and production stages in real time.',
    answerBn: 'হ্যাঁ। প্রতিটি অর্ডারের সাথে মিডিয়া রোল, কাঁচামালের ব্যবহার এবং কাজের অগ্রগতি সরাসরি দেখা যায়।',
    enabled: true,
    order: 3,
  },
  {
    id: 'faq-4',
    questionEn: 'Can I manage employees?',
    questionBn: 'কর্মীদের কাজ ও দায়িত্ব কি পরিচালনা করা যায়?',
    answerEn: 'Yes. Assign jobs to operators, track daily attendance, and control departmental permissions.',
    answerBn: 'হ্যাঁ। অপারেটরদের কাজ বণ্টন, দৈনিক হাজিরা এবং বিভাগভিত্তিক দায়িত্ব সহজেই নিয়ন্ত্রণ করা যায়।',
    enabled: true,
    order: 4,
  },
  {
    id: 'faq-5',
    questionEn: 'Can I use PrintFlow on mobile?',
    questionBn: 'মোবাইল থেকে কি প্রিন্টফ্লো ব্যবহার করা যায়?',
    answerEn: 'Yes. PrintFlow is fully responsive and runs smoothly in any mobile or tablet browser.',
    answerBn: 'হ্যাঁ। প্রিন্টফ্লো সম্পূর্ণ রেসপনসিভ এবং যেকোনো স্মার্টফোন বা ট্যাবলেটে স্বাচ্ছন্দ্যে ব্যবহারযোগ্য।',
    enabled: true,
    order: 5,
  },
  {
    id: 'faq-6',
    questionEn: 'Can I track customer dues?',
    questionBn: 'গ্রাহকদের বকেয়া কি ট্র্যাক করা যায়?',
    answerEn: 'Yes. Track customer balances with clear ledgers and send payment reminders.',
    answerBn: 'হ্যাঁ। গ্রাহকভিত্তিক বাকি টাকার হিসাব এবং পেমেন্ট রিমাইন্ডার পাঠানোর পূর্ণ সুবিধা রয়েছে।',
    enabled: true,
    order: 6,
  },
  {
    id: 'faq-7',
    questionEn: 'Can I start with a free trial?',
    questionBn: 'ফ্রি ট্রায়াল দিয়ে কি শুরু করা যাবে?',
    answerEn: 'Yes. You can start a free trial immediately without needing a credit card.',
    answerBn: 'হ্যাঁ। কোনো ক্রেডিট কার্ড ছাড়াই এখনই ফ্রি ট্রায়াল শুরু করতে পারেন।',
    enabled: true,
    order: 7,
  },
]

export const DEFAULT_LANDING_CONFIG: LandingPageConfig = {
  general: {
    enabled: true,
    defaultLanguage: 'en',
    theme: 'system',
  },
  sections: DEFAULT_LANDING_SECTIONS,
  hero: {
    eyebrowEn: 'Print & Signage Management Software',
    eyebrowBn: 'প্রিন্ট ও সাইনেজ ম্যানেজমেন্ট সফটওয়্যার',
    headlineEn: 'Run Your Print & Signage Business Without the Chaos.',
    headlineBn: 'আপনার প্রিন্ট ব্যবসার সব কাজ এক জায়গায় পরিচালনা করুন।',
    descriptionEn:
      'Sales, design, production, inventory, employees, delivery and payments — connected in one place.',
    descriptionBn:
      'সেলস, ডিজাইন, প্রোডাকশন, ইনভেন্টরি, কর্মচারী, ডেলিভারি ও পেমেন্ট — সব এক সাথে সংযুক্ত।',
    primaryCtaEn: 'Start Free Trial',
    primaryCtaBn: 'ফ্রি ট্রায়াল শুরু করুন',
    primaryCtaLink: '/register',
    secondaryCtaEn: 'See How It Works',
    secondaryCtaBn: 'কাজের ধাপ দেখুন',
    secondaryCtaLink: '#workflow',
  },
  companies: [],
  pricing: {
    showPricing: true,
    showMonthly: true,
    showYearly: true,
    featuredPlanCode: 'business',
    titleEn: 'Simple Pricing. Start Small.',
    titleBn: 'সহজ মূল্যতালিকা। ছোট থেকেই শুরু করুন।',
    descriptionEn: 'Select the right plan for your business and upgrade anytime.',
    descriptionBn: 'আপনার ব্যবসার জন্য উপযুক্ত প্ল্যান বেছে নিন এবং প্রয়োজন অনুযায়ী আপগ্রেড করুন।',
  },
  faq: DEFAULT_LANDING_FAQ,
  seo: {
    metaTitle: 'PrintFlow — Print & Signage Business Management Software',
    metaDescription:
      'Manage sales, design, production, inventory, employees, delivery and payments with PrintFlow.',
    ogImageUrl: '/og-image.png',
    canonicalUrl: 'https://printflow.bd',
  },
}
