// ==============================================================================
// PrintFlow SaaS - Authoritative Landing Page Default Configuration
// Strictly aligned with Master Implementation Prompt copy and structure rules
// ==============================================================================

import type {
  LandingPageConfig,
  LandingCompanyConfig,
  LandingComparisonConfig,
  LandingCompaniesSectionConfig,
  LandingFinalCtaConfig,
} from '@/types/landing-page.types'

export const DEFAULT_LANDING_SECTIONS = [
  {
    id: 'hero',
    key: 'hero',
    nameEn: 'Hero',
    nameBn: 'হিরো সেকশন',
    enabled: true,
    order: 1,
  },
  {
    id: 'without_printflow',
    key: 'without_printflow',
    nameEn: 'Without PrintFlow',
    nameBn: 'প্রিন্টফ্লো ছাড়া অবস্থা',
    enabled: true,
    order: 2,
  },
  {
    id: 'with_printflow',
    key: 'with_printflow',
    nameEn: 'With PrintFlow',
    nameBn: 'প্রিন্টফ্লো ব্যবহারের সুবিধা',
    enabled: true,
    order: 3,
  },
  {
    id: 'workflow',
    key: 'workflow',
    nameEn: 'Workflow',
    nameBn: 'মূল কাজের ধাপ',
    enabled: true,
    order: 4,
  },
  {
    id: 'employees',
    key: 'employees',
    nameEn: 'Employees',
    nameBn: 'কর্মী ব্যবস্থাপনা',
    enabled: true,
    order: 5,
  },
  {
    id: 'what_we_manage',
    key: 'what_we_manage',
    nameEn: 'What PrintFlow Manages',
    nameBn: 'যা কিছু পরিচালনা করা যায়',
    enabled: true,
    order: 6,
  },
  {
    id: 'industries',
    key: 'industries',
    nameEn: 'Industries',
    nameBn: 'শিল্প খাত',
    enabled: true,
    order: 7,
  },
  {
    id: 'companies',
    key: 'companies',
    nameEn: 'Registered Companies',
    nameBn: 'নিবন্ধিত প্রতিষ্ঠান',
    enabled: true,
    order: 8,
  },
  {
    id: 'bangladesh',
    key: 'bangladesh',
    nameEn: 'Bangladesh',
    nameBn: 'বাংলাদেশ ফিচার',
    enabled: true,
    order: 9,
  },
  {
    id: 'mobile',
    key: 'mobile',
    nameEn: 'Mobile',
    nameBn: 'মোবাইল ব্যবহার',
    enabled: true,
    order: 10,
  },
  {
    id: 'pricing',
    key: 'pricing',
    nameEn: 'Pricing',
    nameBn: 'মূল্যতালিকা',
    enabled: true,
    order: 11,
  },
  {
    id: 'faq',
    key: 'faq',
    nameEn: 'FAQ',
    nameBn: 'সাধারণ প্রশ্নোত্তর',
    enabled: true,
    order: 12,
  },
  {
    id: 'final_cta',
    key: 'final_cta',
    nameEn: 'Final CTA',
    nameBn: 'চূড়ান্ত আহ্বান',
    enabled: true,
    order: 13,
  },
]

export const DEFAULT_LANDING_FAQ = [
  {
    id: 'faq-1',
    questionEn: 'What is PrintFlow?',
    questionBn: 'প্রিন্টফ্লো কী?',
    answerEn: 'Business management software built specifically for print and signage businesses.',
    answerBn: 'প্রিন্ট এবং সাইনেজ ব্যবসার সব কাজ এক সাথে পরিচালনা করার আধুনিক সফটওয়্যার।',
    enabled: true,
    order: 1,
  },
  {
    id: 'faq-2',
    questionEn: 'Who is PrintFlow for?',
    questionBn: 'প্রিন্টফ্লো কাদের জন্য উপযোগী?',
    answerEn: 'Digital print shops, offset presses, flex & banner makers, acrylic/LED fabricators, and installation teams.',
    answerBn: 'ডিজিটাল প্রিন্ট, অফসেট প্রেস, ফ্লেক্স-ব্যানার ও সাইনেজ তৈরির সব ধরনের প্রতিষ্ঠানের জন্য।',
    enabled: true,
    order: 2,
  },
  {
    id: 'faq-3',
    questionEn: 'Can I manage production and inventory?',
    questionBn: 'প্রোডাকশন এবং ইনভেন্টরি কি একসাথে নিয়ন্ত্রণ করা সম্ভব?',
    answerEn: 'Yes. Every job order automatically tracks media rolls, sheet stock, and production stages in real time.',
    answerBn: 'হ্যাঁ। প্রতিটি অর্ডারের সাথে মিডিয়া রোল, কাঁচামালের ব্যবহার এবং কাজের অগ্রগতি সরাসরি দেখা যায়।',
    enabled: true,
    order: 3,
  },
  {
    id: 'faq-4',
    questionEn: 'Can I manage employees?',
    questionBn: 'কর্মীদের কাজ ও দায়িত্ব কি পরিচালনা করা যায়?',
    answerEn: 'Yes. Assign jobs to operators, track daily attendance, and control departmental permissions.',
    answerBn: 'হ্যাঁ। অপারেটরদের কাজ বণ্টন, দৈনিক হাজিরা এবং বিভাগভিত্তিক দায়িত্ব সহজেই নিয়ন্ত্রণ করা যায়।',
    enabled: true,
    order: 4,
  },
  {
    id: 'faq-5',
    questionEn: 'Can I use PrintFlow on mobile?',
    questionBn: 'মোবাইল থেকে কি প্রিন্টফ্লো ব্যবহার করা যায়?',
    answerEn: 'Yes. PrintFlow is fully responsive and runs smoothly in any mobile or tablet browser.',
    answerBn: 'হ্যাঁ। প্রিন্টফ্লো সম্পূর্ণ রেসপনসিভ এবং যেকোনো স্মার্টফোন বা ট্যাবলেটে স্বাচ্ছন্দ্যে ব্যবহারযোগ্য।',
    enabled: true,
    order: 5,
  },
  {
    id: 'faq-6',
    questionEn: 'Can I track customer dues?',
    questionBn: 'গ্রাহকদের বকেয়া কি ট্র্যাক করা যায়?',
    answerEn: 'Yes. Track customer balances with clear ledgers and send payment reminders.',
    answerBn: 'হ্যাঁ। গ্রাহকভিত্তিক বাকি টাকার হিসাব এবং পেমেন্ট রিমাইন্ডার পাঠানোর পূর্ণ সুবিধা রয়েছে।',
    enabled: true,
    order: 6,
  },
  {
    id: 'faq-7',
    questionEn: 'Can I start with a free trial?',
    questionBn: 'ফ্রি ট্রায়াল দিয়ে কি শুরু করা যাবে?',
    answerEn: 'Yes. You can start a free trial immediately without needing a credit card.',
    answerBn: 'হ্যাঁ। কোনো ক্রেডিট কার্ড ছাড়াই এখনই ফ্রি ট্রায়াল শুরু করতে পারেন।',
    enabled: true,
    order: 7,
  },
]

export const DEFAULT_LANDING_COMPANIES: LandingCompanyConfig[] = [
  {
    id: 'comp-1',
    name: 'Meghna Digital Press',
    logoUrl: '/logo.png',
    city: 'Arambagh, Dhaka',
    isPublic: true,
    status: 'active',
    displayMode: 'logo_name',
    order: 1,
  },
  {
    id: 'comp-2',
    name: 'Apex Media & Signage',
    logoUrl: '/printflow-logo.png',
    city: 'Anderkilla, Chattogram',
    isPublic: true,
    status: 'active',
    displayMode: 'logo_name',
    order: 2,
  },
  {
    id: 'comp-3',
    name: 'Padma Flex & Signage',
    logoUrl: '/icon-192.png',
    city: 'Station Road, Bogura',
    isPublic: true,
    status: 'active',
    displayMode: 'logo_name',
    order: 3,
  },
  {
    id: 'comp-4',
    name: 'Surma Offset & Packaging',
    logoUrl: '/logo.png',
    city: 'Zindabazar, Sylhet',
    isPublic: true,
    status: 'active',
    displayMode: 'logo_name',
    order: 4,
  },
  {
    id: 'comp-5',
    name: 'Jamuna Backlit Studio',
    logoUrl: '/printflow-logo.png',
    city: 'Chowrasta, Gazipur',
    isPublic: true,
    status: 'active',
    displayMode: 'logo_name',
    order: 5,
  },
  {
    id: 'comp-6',
    name: 'Dhaka Color Lab & Print',
    logoUrl: '/icon-192.png',
    city: 'Motijheel, Dhaka',
    isPublic: true,
    status: 'active',
    displayMode: 'logo_name',
    order: 6,
  },
  {
    id: 'comp-7',
    name: 'Prime Sign & Fabrication',
    logoUrl: '/logo.png',
    city: 'Fakirapool, Dhaka',
    isPublic: true,
    status: 'active',
    displayMode: 'logo_name',
    order: 7,
  },
  {
    id: 'comp-8',
    name: 'National Digital Banner',
    logoUrl: '/printflow-logo.png',
    city: 'Banglamotor, Dhaka',
    isPublic: true,
    status: 'active',
    displayMode: 'logo_name',
    order: 8,
  },
]

export const DEFAULT_COMPARISON_CONFIG: LandingComparisonConfig = {
  eyebrowEn: 'Operational Comparison',
  eyebrowBn: 'কাজের বাস্তব পার্থক্য',
  headlineEn: 'Old Press Chaos vs. The PrintFlow Way',
  headlineBn: 'প্রচলিত প্রেসের বিশৃঙ্খলা বনাম আধুনিক প্রিন্টফ্লো',
  descriptionEn:
    'Replace torn paper slips, roll shortages, and forgotten dues with a single connected system.',
  descriptionBn:
    'ছেঁড়া কাগজের স্লিপ, রোলের সংকট ও বকেয়ার ঝামেলা ভুলে শুরু করুন আধুনিক ক্লাউড প্রেস।',
  withoutTitleEn: 'Without PrintFlow (Traditional Paper Chaos)',
  withoutTitleBn: 'প্রিন্টফ্লো ছাড়া অবস্থা (কাগজের বিশৃঙ্খলা)',
  withTitleEn: 'With PrintFlow (Connected Cloud System)',
  withTitleBn: 'প্রিন্টফ্লো সহ (সংযুক্ত ক্লাউড সিস্টেম)',
  items: [
    {
      id: 'cmp-1',
      categoryEn: 'Job Tickets & Instructions',
      categoryBn: 'কাজের নির্দেশনা ও স্লিপ',
      beforeEn: 'Torn paper slips stained by solvent ink. Misprints and lost specs come out of your own pocket.',
      beforeBn: 'ছেঁড়া কাগজে হাতে লেখা স্লিপ কালিতে নষ্ট বা হারিয়ে যায়; ভুল প্রিন্টের লোকসান নিজের পকেট থেকে যায়।',
      afterEn: 'Barcoded digital job tickets with dimensions, roll code, and artwork preview. 100% accurate.',
      afterBn: 'নিখুঁত মাপ, রোল কোড ও আর্টওয়ার্ক প্রাকদর্শন সম্বলিত ডিজিটাল বারকোড জব টিকিট। ০% ভুল প্রিন্ট।',
      beforeTagEn: 'Costly Misprints',
      beforeTagBn: 'ভুল প্রিন্ট ও লোকসান',
      afterTagEn: '100% Accurate Jobs',
      afterTagBn: '১০০% সঠিক প্রিন্ট',
    },
    {
      id: 'cmp-2',
      categoryEn: 'Roll Media Inventory',
      categoryBn: 'রোল স্টক ও কাঁচামাল',
      beforeEn: 'Flex rolls run out unexpectedly at 10 PM mid-job. Press sits idle while scrambling for stock.',
      beforeBn: 'রাত ১০টায় জরুরি প্রিন্টের মাঝপথে রোল শেষ। মেশিন বন্ধ থাকে আর মেটেরিয়াল খুঁজতে ছোটাছুটি।',
      afterEn: 'Master rolls tracked by width & length. Real-time SFT deductions and low-stock alerts.',
      afterBn: 'প্রস্থ ও দৈর্ঘ্য অনুযায়ী রিয়েল-টাইম স্কয়ারফিট স্টক হিসাব এবং রোল শেষ হওয়ার আগেই অ্যালার্ট।',
      beforeTagEn: 'Mid-Job Outages',
      beforeTagBn: 'মাঝপথে কাজ বন্ধ',
      afterTagEn: 'Real-Time Roll SFT',
      afterTagBn: 'লাইভ স্কয়ারফিট স্টক',
    },
    {
      id: 'cmp-3',
      categoryEn: 'Remnant Offcut Scrap',
      categoryBn: 'কাটিং স্ক্র্যাপ ও অপচয়',
      beforeEn: 'Leftover 3–5ft roll cutoffs thrown into trash as garbage. Thousands of Takas lost weekly.',
      beforeBn: 'অর্ডারের পর বেঁচে যাওয়া ৩–৫ ফুটের কাটিং টুকরো ফেলে দেওয়া হয়; প্রতি মাসে হাজার টাকার অপচয়।',
      afterEn: 'Scrap Salvage Engine catalogs remnant offcuts so operators reuse them for stickers & standees.',
      afterBn: 'কাটিং স্ক্র্যাপ ইঞ্জিন ব্যবহারযোগ্য টুকরো সংরক্ষণ করে ছোট স্টিকার প্রিন্ট করে বাড়তি লাভ।',
      beforeTagEn: 'Daily Scrap Loss',
      beforeTagBn: 'হাজার টাকার অপচয়',
      afterTagEn: 'Zero Scrap Wasted',
      afterTagBn: 'অপচয় রোধ ও বাড়তি লাভ',
    },
    {
      id: 'cmp-4',
      categoryEn: 'Floor Progress Chasing',
      categoryBn: 'কারখানা ফলো-আপ ও ফোন',
      beforeEn: 'Calling operators every 20 minutes to ask if the print is ready, interrupting machine focus.',
      beforeBn: 'কাজ শুরু হইছে কি না জানতে অপারেটরকে সারাদিন ফোন কল; কাজের মনোযোগ নষ্ট হয়।',
      afterEn: 'Live machine queue shows real-time Flora, Konica & CNC bed progress with zero phone calls.',
      afterBn: 'লাইভ ফ্লোর স্ক্রিনে ফ্লোরা, কনিকা ও সিএনসি মেশিনের অগ্রগতি এক নজরে দৃশ্যমান; কোনো ফোন ছাড়াই।',
      beforeTagEn: 'Constant Phone Calls',
      beforeTagBn: 'অবিরাম ফোন কলের ক্লান্তি',
      afterTagEn: 'Live Machine Screen',
      afterTagBn: 'এক স্ক্রিনে লাইভ স্ট্যাটাস',
    },
    {
      id: 'cmp-5',
      categoryEn: 'Customer Credit & Dues',
      categoryBn: 'গ্রাহকের বকেয়া খাতা',
      beforeEn: 'Customer credit forgotten in paper khatas. Overdue balances sit uncollected for months.',
      beforeBn: 'খাতায় লিখে রাখা বাকি টাকা আদায় করতে ভুলে যাওয়া; মাসের পর মাস লাখ টাকা বকেয়া পড়ে থাকা।',
      afterEn: 'Instant due ledger with 1-click WhatsApp reminders and embedded bKash payment QR codes.',
      afterBn: 'গ্রাহকভিত্তিক বকেয়া হিসাব এবং মাত্র ১ ক্লিকে হোয়াটসঅ্যাপে বিকাশ কিউআরসহ স্বয়ংক্রিয় রিমাইন্ডার।',
      beforeTagEn: 'Uncollected Cash',
      beforeTagBn: 'বকেয়া টাকা আটকে থাকা',
      afterTagEn: '1-Click Recovery',
      afterTagBn: 'দ্রুত বকেয়া আদায়',
    },
    {
      id: 'cmp-6',
      categoryEn: 'Employee Attendance & Payroll',
      categoryBn: 'হাজিরা খাতা ও ওভারটাইম',
      beforeEn: 'Paper registers allow buddy punching, late arrival disputes, and disputed overtime payroll.',
      beforeBn: 'খাতায় সই করে প্রক্সি হাজিরা, দেরিতে আসা নিয়ে তর্ক এবং মাসের শেষে ওভারটাইম নিয়ে ঝামেলা।',
      afterEn: 'Camera QR check-in on mobile/tablet with shop geofencing and automatic payroll.',
      afterBn: 'মোবাইল বা ট্যাবলেটের ক্যামেরায় কিউআর স্ক্যান করে মুহূর্তেই হাজিরা ও নিখুঁত বেতন হিসাব।',
      beforeTagEn: 'Attendance Disputes',
      beforeTagBn: 'প্রক্সি হাজিরা ও ঝামেলা',
      afterTagEn: 'Smart QR Terminal',
      afterTagBn: 'স্মার্ট কিউআর হাজিরা',
    },
  ],
}

export const DEFAULT_COMPANIES_SECTION_CONFIG: LandingCompaniesSectionConfig = {
  eyebrowEn: 'Verified Print Network',
  eyebrowBn: 'বিশ্বস্ত নেটওয়ার্ক',
  headlineEn: 'Trusted by Leading Print & Signage Shops Across Bangladesh',
  headlineBn: 'সারা দেশের শীর্ষ প্রিন্ট ও সাইনেজ শপের বিশ্বস্ত পছন্দ',
  descriptionEn:
    'Powering high-volume commercial offset presses, digital banner shops, and signage fabricators.',
  descriptionBn:
    'বাণিজ্যিক অফসেট প্রেস, ডিজিটাল ব্যানার শপ ও সাইনেজ কারখানা।',
  autoScroll: true,
  scrollSpeed: 'medium',
}

export const DEFAULT_FINAL_CTA_CONFIG: LandingFinalCtaConfig = {
  eyebrowEn: 'Instant Cloud Onboarding',
  eyebrowBn: 'ইনস্ট্যান্ট ক্লাউড অনবোর্ডিং',
  headlineEn: 'Ready to Take Total Control of Your Print Shop?',
  headlineBn: 'আপনার পুরো প্রেসের সম্পূর্ণ নিয়ন্ত্রণ নিতে প্রস্তুত?',
  descriptionEn:
    'Quotes, roll media stock, floor machines, and staff QR attendance in one connected system.',
  descriptionBn:
    'কোটেশন, রোল স্টক, মেশিন কিউ এবং কিউআর হাজিরা — সব এক সিস্টেমে।',
  primaryCtaEn: 'Start 14-Day Free Trial',
  primaryCtaBn: '১৪ দিনের ফ্রি ট্রায়াল শুরু করুন',
  primaryCtaLink: '/register',
  secondaryCtaEn: 'Book a Live Demo',
  secondaryCtaBn: 'লাইভ ডেমো দেখুন',
}

export const DEFAULT_LANDING_CONFIG: LandingPageConfig = {
  general: {
    enabled: true,
    defaultLanguage: 'en',
    theme: 'system',
  },
  sections: DEFAULT_LANDING_SECTIONS,
  hero: {
    eyebrowEn: 'Cloud ERP for Bangladesh Print & Signage',
    eyebrowBn: 'বাংলাদেশের প্রিন্ট ও সাইনেজ ব্যবসার আধুনিক ইআরপি',
    headlineEn: 'Stop Running Your Print Shop on Paper Slips.',
    headlineBn: 'কাগজের চিরকুট ভুলে পুরো প্রেস চালান ক্লাউডে।',
    descriptionEn:
      'SFT billing, roll media stock, live machine queues, and bKash dues — all in one simple screen.',
    descriptionBn:
      'স্কয়ারফিট বিলিং, রোল স্টক, মেশিনের লাইভ কিউ ও বকেয়া আদায় — সব এক সহজ স্ক্রিনে।',
    primaryCtaEn: 'Start 14-Day Free Trial',
    primaryCtaBn: '১৪ দিনের ফ্রি ট্রায়াল শুরু করুন',
    primaryCtaLink: '/register',
    secondaryCtaEn: 'Book a Live Demo',
    secondaryCtaBn: 'লাইভ ডেমো দেখুন',
    secondaryCtaLink: '#workflow',
  },
  comparison: DEFAULT_COMPARISON_CONFIG,
  companies: DEFAULT_LANDING_COMPANIES,
  companiesSection: DEFAULT_COMPANIES_SECTION_CONFIG,
  pricing: {
    showPricing: true,
    showMonthly: true,
    showYearly: true,
    featuredPlanCode: 'business',
    titleEn: 'Simple Pricing. Start Small.',
    titleBn: 'সহজ মূল্যতালিকা। ছোট থেকেই শুরু করুন।',
    descriptionEn: 'Select the right plan for your business and upgrade anytime.',
    descriptionBn: 'আপনার ব্যবসার জন্য উপযুক্ত প্ল্যান বেছে নিন এবং প্রয়োজন অনুযায়ী আপগ্রেড করুন।',
  },
  faq: DEFAULT_LANDING_FAQ,
  finalCta: DEFAULT_FINAL_CTA_CONFIG,
  seo: {
    metaTitle: 'PrintFlow — Print & Signage Business Management Software',
    metaDescription:
      'Manage sales, design, production, inventory, employees, delivery and payments with PrintFlow.',
    ogImageUrl: '/og-image.png',
    canonicalUrl: 'https://printflow.bd',
  },
}
