import {
  Printer,
  FileText,
  Clock,
  Layers,
  Wrench,
  Truck,
  DollarSign,
  TrendingUp,
  Users,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  Smartphone,
  CreditCard,
  Building2,
  Package,
  Sparkles,
  Boxes,
  HelpCircle,
  Scissors,
  Lightbulb,
  Zap,
  BarChart3,
  Compass,
  Briefcase,
  Flame,
  LayoutGrid,
} from 'lucide-react'

export interface NavItem {
  labelEn: string
  labelBn: string
  href: string
}

export const MARKETING_NAV_ITEMS: NavItem[] = [
  { labelEn: 'Features', labelBn: 'ফিচারসমূহ', href: '#what-we-manage' },
  { labelEn: 'Workflow', labelBn: 'কাজের ধাপ', href: '#workflow' },
  { labelEn: 'QR Attendance', labelBn: 'কিউআর হাজিরা', href: '#employees' },
  { labelEn: 'Industries', labelBn: 'ইন্ডাস্ট্রি', href: '#industries' },
  { labelEn: 'Pricing', labelBn: 'মূল্যতালিকা', href: '#pricing' },
]

export const TRUST_TAGS = [
  'Digital Print',
  'Offset Press',
  'Flex & Banner',
  'Signage',
  'Fabrication',
  'Installation',
]

// 3. How Print Shops Work With PrintFlow: 8 Connected Steps
export const CONNECTED_WORKFLOW_STEPS = [
  {
    step: '01',
    icon: FileText,
    titleEn: 'Quotation',
    titleBn: 'কোটেশন',
    descEn: 'Create professional quotes with measurements (inch/ft/sft), materials, and finishing add-ons.',
    descBn: 'ইঞ্চি, ফুট ও স্কয়ারফিট পরিমাপ, মেটেরিয়াল রেট এবং ফিনিশিং যোগ করে কয়েক সেকেন্ডে কোটেশন তৈরি।',
  },
  {
    step: '02',
    icon: CheckCircle2,
    titleEn: 'Order Booking',
    titleBn: 'অর্ডার নিশ্চিতকরণ',
    descEn: 'Convert approved quotes into official jobs with automated sequential numbering.',
    descBn: 'অনুমোদিত কোটেশনকে ১ ক্লিকে সিরিয়াল নম্বরযুক্ত প্রাতিষ্ঠানিক অর্ডারে রূপান্তর।',
  },
  {
    step: '03',
    icon: Layers,
    titleEn: 'Artwork Design',
    titleBn: 'ডিজাইন ও ফাইল',
    descEn: 'Attach artwork proofs, manage client revision requests, and store production files.',
    descBn: 'গ্রাহকের আর্টওয়ার্ক সংযুক্তকরণ, সংশোধন ট্র্যাকিং এবং প্রিন্ট-রেডি ফাইল সংরক্ষণ।',
  },
  {
    step: '04',
    icon: ShieldCheck,
    titleEn: 'Proof Approval',
    titleBn: 'প্রুফ অনুমোদন',
    descEn: 'Collect digital client sign-off before loading media rolls onto machines.',
    descBn: 'মেশিনে মেটেরিয়াল বা কাগজ লোড করার আগে গ্রাহকের কাছ থেকে ডিজিটাল প্রুফ অনুমোদন।',
  },
  {
    step: '05',
    icon: Printer,
    titleEn: 'Floor Production',
    titleBn: 'মেশিন প্রোডাকশন',
    descEn: 'Move jobs through RIP, printing, lamination, CNC die-cutting, and fabrication queues.',
    descBn: 'প্রিন্ট, লেমিনেশন, ডাই-কাটিং ও মেটাল ফ্যাব্রিকেশনের প্রতিটি ধাপ স্ক্রিনে মনিটর।',
  },
  {
    step: '06',
    icon: Boxes,
    titleEn: 'Material Inventory',
    titleBn: 'মেটেরিয়াল ইনভেন্টরি',
    descEn: 'Deduct exact square footage and roll scrap in real time as jobs complete.',
    descBn: 'কাজ শেষ হওয়ামাত্র রোল স্টক থেকে ব্যবহৃত স্কয়ারফিট ও অপচয়ের হিসাব স্বয়ংক্রিয় সমন্বয়।',
  },
  {
    step: '07',
    icon: Truck,
    titleEn: 'Delivery Challan',
    titleBn: 'চালান ও ডেলিভারি',
    descEn: 'Issue traditional delivery challans and assign dispatch or site-fitting teams.',
    descBn: 'এনবিআর স্বীকৃত ডেলিভারি চালান প্রিন্ট এবং ডেলিভারি বা অন-সাইট ফিটিং টিম বরাদ্দ।',
  },
  {
    step: '08',
    icon: CreditCard,
    titleEn: 'Payment & Dues',
    titleBn: 'পেমেন্ট ও বকেয়া',
    descEn: 'Record cash, bank, or MFS payments and follow up outstanding balances via WhatsApp.',
    descBn: 'ক্যাশ, ব্যাংক বা মোবাইল পেমেন্ট রেকর্ড এবং ১ ক্লিকে হোয়াটসঅ্যাপে বকেয়া তাগাদা।',
  },
]

// 4. Core Problems: Before vs After
export const PROBLEMS_BEFORE_AFTER = [
  {
    categoryEn: 'Quotations',
    categoryBn: 'কোটেশন প্রক্রিয়া',
    beforeEn: 'Prices scattered across WhatsApp chats; verbal quotes forgotten, leading to billing disputes.',
    beforeBn: 'হোয়াটসঅ্যাপ চ্যাটে বিচ্ছিন্ন কোটেশন; মৌখিক দর ভুলে গিয়ে বিল করার সময় ভুল বোঝাবুঝি।',
    afterEn: 'Instant branded PDF quotes calculated with accurate SFT rates, finishing, and VAT.',
    afterBn: 'স্কয়ারফিট রেট, ফিনিশিং ও ভ্যাটসহ নিখুঁত ব্র্যান্ডেড পিডিএফ কোটেশন প্রস্তুত।',
  },
  {
    categoryEn: 'Job Instructions',
    categoryBn: 'কাজের নির্দেশনা',
    beforeEn: 'Handwritten slips on torn paper get stained by solvent ink, torn, or misplaced on the floor.',
    beforeBn: 'ছেঁড়া কাগজে হাতে লেখা স্লিপ কালিতে নষ্ট হয়ে যায় বা কারখানার ফ্লোরে হারিয়ে যায়।',
    afterEn: 'Centralized digital job tickets with dimensions, roll code, finishing notes, and artwork preview.',
    afterBn: 'মাপ, রোল কোড, ফিনিশিং ও আর্টওয়ার্ক প্রাকদর্শন সম্বলিত কেন্দ্রীয় ডিজিটাল জব টিকিট।',
  },
  {
    categoryEn: 'Production Follow-up',
    categoryBn: 'কারখানা ফলো-আপ',
    beforeEn: 'Continuous phone calls between sales desk and operators to ask which job is printing.',
    beforeBn: 'কোন কাজ কোন মেশিনে চলছে তা জানতে সেলস ও অপারেটরদের মধ্যে অবিরাম ফোন কল।',
    afterEn: 'Visual production queue showing which machine is running, queued, or ready for finishing.',
    afterBn: 'কোন মেশিনে কাজ চলছে, কোনটা লাইনে আছে এবং কোনটা রেডি তা এক স্ক্রিনে দৃশ্যমান।',
  },
  {
    categoryEn: 'Media & Roll Tracking',
    categoryBn: 'রোল স্টক ও অপচয়',
    beforeEn: 'Flex rolls and inks run out unexpectedly, forcing emergency runs to the market at night.',
    beforeBn: 'ফ্লেক্স রোল বা কালি কখন শেষ হলো তা জানা যায় না; রাতে জরুরি মেটেরিয়াল কিনতে ছোটাছুটি।',
    afterEn: 'Master rolls tracked by width and length; remaining square footage and scrap recorded automatically.',
    afterBn: 'রোলের প্রস্থ ও দৈর্ঘ্য অনুযায়ী অবশিষ্ট স্কয়ারফিট ও অপচয় স্বয়ংক্রিয়ভাবে ট্র্যাকিং।',
  },
  {
    categoryEn: 'Customer Dues',
    categoryBn: 'গ্রাহকের বকেয়া খাতা',
    beforeEn: 'Customer credit forgotten in paper diaries; uncollected dues accumulate for months.',
    beforeBn: 'খাতায় লিখে রাখা বাকি টাকা আদায় করতে ভুলে যাওয়া; মাসের পর মাস বকেয়া পড়ে থাকা।',
    afterEn: 'Clear overdue ledger with 1-click polite payment reminder messages sent directly to WhatsApp.',
    afterBn: 'গ্রাহকভিত্তিক বকেয়া হিসাব এবং ১ ক্লিকে হোয়াটসঅ্যাপে স্বয়ংক্রিয় পেমেন্ট রিমাইন্ডার।',
  },
  {
    categoryEn: 'Job Profitability',
    categoryBn: 'অর্ডারের লাভ-ক্ষতি',
    beforeEn: 'Owners guess profits without knowing the real cost of media, ink, labor, and electricity.',
    beforeBn: 'মিডিয়া, কালি, অপারেটরের মজুরি ও বিদ্যুৎ খরচ না জেনেই অনুমানে লাভ নির্ধারণ।',
    afterEn: 'Automated BOM costing deducting materials, labor, and finishing to show true net margin.',
    afterBn: 'মেটেরিয়াল, লেবার ও ফিনিশিং খরচ বাদ দিয়ে প্রতিটি কাজের আসল নেট মুনাফা দৃশ্যমান।',
  },
]

// 5. Core Workflow Lifecycle Steps
export const CORE_WORKFLOW_LIFECYCLE = [
  {
    id: 'customer',
    titleEn: 'Customer Request',
    titleBn: 'গ্রাহকের চাহিদা',
    descEn: 'Customer provides dimensions, media specifications, and delivery target.',
    descBn: 'গ্রাহকের কাছ থেকে কাজের সাইজ, মেটেরিয়াল ও সময়সীমা গ্রহণ।',
  },
  {
    id: 'quotation',
    titleEn: 'Quotation / Work Request',
    titleBn: 'কোটেশন বা কাজের রিকোয়েস্ট',
    descEn: 'Calculate SFT, minimum billable area, finishing charges, and generate PDF.',
    descBn: 'স্কয়ারফিট, নূন্যতম বিলিং এলাকা ও ফিনিশিং রেট হিসাব করে কোটেশন প্রস্তুত।',
  },
  {
    id: 'order',
    titleEn: 'Invoice / Order Booking',
    titleBn: 'অর্ডার ও ইনভয়েস বুকিং',
    descEn: 'Record advance deposit, assign order number, and confirm order.',
    descBn: 'অগ্রিম পেমেন্ট গ্রহণ এবং ধারাবাহিক নম্বর দিয়ে অর্ডার নিশ্চিতকরণ।',
  },
  {
    id: 'design',
    titleEn: 'Design & Proof Approval',
    titleBn: 'ডিজাইন ও প্রুফ অনুমোদন',
    descEn: 'Pre-press designer uploads proof; customer approves digital preview.',
    descBn: 'ডিজাইনার প্রুফ আপলোড করেন এবং গ্রাহক দেখে ফাইনাল সাইন-অফ দেন।',
  },
  {
    id: 'job_order',
    titleEn: 'Job Orders (Multi-Department)',
    titleBn: 'জব টিকিট (বিভাগ ভিত্তিক)',
    descEn: 'One invoice fans out into print, lamination, and fabrication tasks.',
    descBn: 'একটি ইনভয়েস থেকে প্রিন্ট, লেমিনেশন ও ফ্রেম মেকিংয়ের একাধিক জব টিকিট তৈরি।',
  },
  {
    id: 'production',
    titleEn: 'Machine Production & QC',
    titleBn: 'মেশিন প্রোডাকশন ও ফিনিশিং',
    descEn: 'Operators print on assigned machines, apply eyelets, and perform quality check.',
    descBn: 'মেশিনে প্রিন্ট সম্পন্ন, আইলেট রিং লাগানো এবং কোয়ালিটি চেকিং।',
  },
  {
    id: 'delivery',
    titleEn: 'Delivery & Site Fitting',
    titleBn: 'চালান ডেলিভারি ও ফিটিং',
    descEn: 'Dispatch with formal challan; capture on-site installation completion proof.',
    descBn: 'চালানসহ মালামাল ডেলিভারি এবং অন-সাইট ফিটিং নিশ্চিতকরণ।',
  },
  {
    id: 'due',
    titleEn: 'Final Payment & Settlement',
    titleBn: 'বকেয়া আদায় ও হিসাব সমাপ্তি',
    descEn: 'Collect balance amount via Cash or MFS and record in financial ledger.',
    descBn: 'বাকি টাকা ক্যাশ বা মোবাইল ব্যাংকিংয়ে আদায় করে লেজার সমন্বয়।',
  },
]

// 6. What PrintFlow Manages: 6 Operational Domains
export const WHAT_PRINTFLOW_MANAGES = [
  {
    id: 'sales',
    titleEn: 'Sales & Quotations',
    titleBn: 'সেলস ও কোটেশন',
    itemsEn: ['Instant SFT Quotations', 'Customer Records & CRM', 'Order Confirmations', 'Sales Invoices', 'Payment Receipts', 'Due Aging Ledgers'],
    itemsBn: ['মুহূর্তে স্কয়ারফিট কোটেশন', 'গ্রাহক তথ্য ও সিআরএম', 'অর্ডার নিশ্চিতকরণ', 'সেলস ইনভয়েস', 'পেমেন্ট মানি রিসিট', 'গ্রাহক বকেয়া খাতা'],
    color: 'blue',
  },
  {
    id: 'production',
    titleEn: 'Production Floor',
    titleBn: 'কারখানা প্রোডাকশন',
    itemsEn: ['Digital Job Tickets', 'Live Machine Queue', 'Large-Format Solvent & UV', 'Cold & Hot Lamination', 'CNC & Laser Fabrication', 'Finishing & Eyelets'],
    itemsBn: ['ডিজিটাল জব টিকিট', 'লাইভ মেশিন কিউ', 'লার্জ ফরম্যাট সলভেন্ট ও ইউভি', 'কোল্ড ও হট লেমিনেশন', 'সিএনসি ও লেজার ফ্যাব্রিকেশন', 'ফিনিশিং ও আইলেট রিং'],
    color: 'emerald',
  },
  {
    id: 'inventory',
    titleEn: 'Inventory & Stock',
    titleBn: 'ইনভেন্টরি ও কাঁচামাল',
    itemsEn: ['Master Roll Stock (Width × Length)', 'Square-Footage Deduction', 'Scrap & Wastage Accounting', 'Acrylic & PVC Sheets', 'LED Modules & Power Supplies', 'Solvent & Offset Inks'],
    itemsBn: ['মাস্টার রোল স্টক (প্রস্থ × দৈর্ঘ্য)', 'স্কয়ারফিট ব্যবহার হিসাব', 'ওয়েস্টেজ ও অপচয় ট্র্যাকিং', 'এক্রিলিক ও পিভিসি বোর্ড', 'এলইডি লাইট ও পাওয়ার সাপ্লাই', 'সলভেন্ট ও অফসেট কালি'],
    color: 'purple',
  },
  {
    id: 'workforce',
    titleEn: 'Workforce & Shifts',
    titleBn: 'কর্মী ও কারখানা শিফট',
    itemsEn: ['Employee Responsibilities', 'Shift & Floor Attendance', 'Operator Job Assignments', 'Overtime Hour Tracking', 'Salary Advance Records', 'Monthly Pay Slip Summary'],
    itemsBn: ['কর্মীভিত্তিক দায়িত্ব বণ্টন', 'শিফট ও ফ্লোর হাজিরা', 'মেশিনে অপারেটর বরাদ্দ', 'ওভারটাইম ঘণ্টা হিসাব', 'অগ্রিম বেতন রেকর্ড', 'মাসিক বেতন বিবরণী'],
    color: 'amber',
  },
  {
    id: 'finance',
    titleEn: 'Finance & Accounts',
    titleBn: 'ফাইন্যান্স ও হিসাবরক্ষণ',
    itemsEn: ['Cash in Hand (Counter)', 'Bank Accounts', 'bKash / Nagad MFS', 'Daily Shop Expenses', 'Supplier Payables', 'True Job Net Profit'],
    itemsBn: ['কাউন্টার ক্যাশ ইন হ্যান্ড', 'ব্যাংক একাউন্ট হিসাব', 'বিকাশ ও নগদ ট্রানজেকশন', 'দৈনিক প্রেসের খরচ', 'সাপ্লায়ার বাকি খাতা', 'প্রতি কাজের আসল নিট লাভ'],
    color: 'cyan',
  },
  {
    id: 'management',
    titleEn: 'Management & Control',
    titleBn: 'ম্যানেজমেন্ট ও অডিট',
    itemsEn: ['Executive Sales Reports', 'Audit Trail & Activity Log', 'Multi-Branch Support', 'Role-Based Permissions (RBAC)', 'Real-Time Notifications', 'Data Security & Backups'],
    itemsBn: ['দৈনিক কালেকশন রিপোর্ট', 'কার্যক্রম অডিট হিস্টোরি', 'একাধিক শাখা পরিচালনা', 'ভূমিকাভিত্তিক পারমিশন', 'রিয়েল-টাইম নোটিফিকেশন', 'ক্লাউড ব্যাকআপ ও নিরাপত্তা'],
    color: 'indigo',
  },
]

// 7. Industry Solutions: 12 Sectors (Concise 1-liners)
export const INDUSTRY_SECTORS = [
  {
    id: 'digital',
    titleEn: 'Digital Printing',
    titleBn: 'ডিজিটাল প্রিন্টিং',
    descEn: 'Fast turnaround visiting cards, brochures, flyers, and certificate short runs.',
    descBn: 'ভিজিটিং কার্ড, ব্রোশার, লিফলেট ও সনদের দ্রুত বুকিং এবং ডেলিভারি।',
    icon: Printer,
  },
  {
    id: 'offset',
    titleEn: 'Offset Commercial Press',
    titleBn: 'অফসেট প্রিন্টিং প্রেস',
    descEn: 'Multi-color book printing, catalogs, master cartons, and CTP plate exposure.',
    descBn: 'বই প্রিন্ট, ক্যাটালগ, লিফলেট এবং ডাই-কাটিং বক্সের সম্পূর্ণ হিসাব।',
    icon: Layers,
  },
  {
    id: 'flex',
    titleEn: 'Flex & Banner Shops',
    titleBn: 'ফ্লেক্স ও ব্যানার শপ',
    descEn: 'Large-format solvent printing, Star Flex, backlit fabric, canvas, and grommet eyelets.',
    descBn: '১০/১২ ফিট সলভেন্ট ব্যানার, স্টার ফ্লেক্স, ব্যাকলিট কাপড় ও আইলেট রিং।',
    icon: LayoutGrid,
  },
  {
    id: 'sticker',
    titleEn: 'Sticker & Label Printers',
    titleBn: 'স্টিকার ও লেবেল',
    descEn: 'Vinyl decals, kiss-cut product labels, reflective sheets, and protective laminations.',
    descBn: 'ভিনাইল স্টিকার, ডাই-কাট লেবেল, রিফ্লেক্টিভ শিট ও প্রটেক্টিভ লেমিনেশন।',
    icon: Scissors,
  },
  {
    id: 'packaging',
    titleEn: 'Carton Packaging Hubs',
    titleBn: 'কার্টন ও প্যাকেজিং',
    descEn: 'Duplex board cartons, garment master boxes, food boxes, spot UV, and die-cutting.',
    descBn: 'ডুপ্লেক্স বোর্ড কার্টন, ফুড বক্স, স্পট ইউভি এবং ডাই-কাটিং পেস্টিং লাইন।',
    icon: Package,
  },
  {
    id: 'acrylic',
    titleEn: 'Acrylic & Laser Studios',
    titleBn: 'এক্রিলিক ও লেজার সাইন',
    descEn: '3D laser-cut acrylic letters, crystal edge signs, and interior directory plates.',
    descBn: 'লেজার কাট এক্রিলিক বর্ণ, ক্রিস্টাল ফ্রেম ও অফিস ডিরেক্টরি প্লেট।',
    icon: Sparkles,
  },
  {
    id: 'led',
    titleEn: 'LED Signboard Makers',
    titleBn: 'এলইডি সাইনবোর্ড',
    descEn: 'Backlit channel letters, moving displays, outdoor P10 video screens, and power supplies.',
    descBn: 'চ্যানেল বর্ণ, এলইডি মুভিং ডিসপ্লে, ভিডিও স্ক্রিন ও পাওয়ার সাপ্লাই।',
    icon: Lightbulb,
  },
  {
    id: 'acp',
    titleEn: 'ACP & PVC Cladding',
    titleBn: 'এসিপি ও পিভিসি বোর্ড',
    descEn: 'Exterior shop fascias, architectural ACP cladding, and PVC foam display boards.',
    descBn: 'দোকানের বহিরাঙ্গন এসিপি বোর্ড ক্ল্যাডিং ও পিভিসি ডিসপ্লে বোর্ড।',
    icon: Building2,
  },
  {
    id: 'vehicle',
    titleEn: 'Vehicle Branding',
    titleBn: 'গাড়ি ব্র্যান্ডিং',
    descEn: 'Corporate car wraps, delivery van decals, and transport promotional branding.',
    descBn: 'ডেলিভারি ভ্যান, কাভার্ড ভ্যান ও কর্পোরেট গাড়ি ব্র্যান্ডিং স্টিকার।',
    icon: Truck,
  },
  {
    id: 'fabrication',
    titleEn: 'Metal & Steel Fabrication',
    titleBn: 'মেটাল ও ফ্রেম ফ্যাব্রিকেশন',
    descEn: 'MS square pipe frames, welding structures, rooftop hoardings, and steel stands.',
    descBn: 'এমএস স্কয়ার পাইপ ফ্রেম, ওয়েল্ডিং কাঠামো ও বহিরাঙ্গন বিলবোর্ড স্ট্যান্ড।',
    icon: Wrench,
  },
  {
    id: 'installation',
    titleEn: 'Installation Contractors',
    titleBn: 'অন-সাইট ইনস্টলেশন',
    descEn: 'Field technician routing, night highway hoarding fixing, and photo completion proof.',
    descBn: 'ফিল্ড ফিটিং টিম বরাদ্দ, হাইওয়ে সাইন স্থাপন ও কাজের ছবি সংরক্ষণ।',
    icon: Compass,
  },
  {
    id: 'agency',
    titleEn: 'Advertising Agencies',
    titleBn: 'বিজ্ঞাপন এজেন্সি',
    descEn: 'Multi-vendor campaign execution, retail kiosk fabrication, and outsourced markups.',
    descBn: 'দেশব্যাপী ব্র্যান্ডিং ক্যাম্পেইন ও থার্ড-পার্টি প্রেস ভেন্ডর সমন্বয়।',
    icon: Briefcase,
  },
]

// 8. Key Operational Advantages: Built Around Real Print Shops
export const KEY_OPERATIONAL_ADVANTAGES = [
  {
    icon: Scissors,
    titleEn: 'Measurement-Based Pricing',
    titleBn: 'পরিমাপ ভিত্তিক স্বয়ংক্রিয় দর',
    descEn: 'Calculates exact costs by inch, foot, square foot, or running foot with minimum billable area rules.',
    descBn: 'ইঞ্চি, ফুট, স্কয়ারফিট ও রানিং ফিট অনুযায়ী সঠিক রেট ও নূন্যতম বিলিং সাইজের স্বয়ংক্রিয় হিসাব।',
  },
  {
    icon: Boxes,
    titleEn: 'Roll-Based Inventory',
    titleBn: 'রোল ভিত্তিক স্টক ট্র্যাকিং',
    descEn: 'Tracks wide media rolls by width and length. Deducts square footage and operator loading scrap automatically.',
    descBn: 'মাস্টার রোলের প্রস্থ ও দৈর্ঘ্য অনুযায়ী অবশিষ্ট স্কয়ারফিট এবং কাটিং অপচয় নিখুঁতভাবে সমন্বয়।',
  },
  {
    icon: Clock,
    titleEn: 'Live Production Visibility',
    titleBn: 'লাইভ প্রোডাকশন ট্র্যাকিং',
    descEn: 'Floor managers see instantly which machines are running, jobs queued, or ready for dispatch.',
    descBn: 'কোন মেশিনে প্রিন্ট চলছে, কোনটা লাইনে আছে এবং কোনটা ডেলিভারির জন্য প্রস্তুত তা এক নজরে জানা।',
  },
  {
    icon: TrendingUp,
    titleEn: 'True Job Costing & Net Margin',
    titleBn: 'প্রকৃত জব কস্টিং ও নিট মুনাফা',
    descEn: 'Deducts actual media, ink, labor, framing hardware, and transport from invoice total to show real net profit.',
    descBn: 'মিডিয়া, কালি, কারিগর মজুরি, ফ্রেম মেটেরিয়াল ও পরিবহন খরচ বাদ দিয়ে আসল লাভ নির্ণয়।',
  },
  {
    icon: CreditCard,
    titleEn: 'Customer Dues Management',
    titleBn: 'বকেয়া খাতা ও অটো রিমাইন্ডার',
    descEn: 'Tracks booking advance, delivery payments, and aging credit. Dispatches polite reminders via WhatsApp.',
    descBn: 'অগ্রিম বুকিং, ডেলিভারি ক্যাশ ও বাকি টাকার পূর্ণাঙ্গ হিসাব এবং হোয়াটসঅ্যাপে ভদ্র তাগাদা প্রেরণ।',
  },
  {
    icon: Flame,
    titleEn: 'Print & Signage Under One System',
    titleBn: 'এক সিস্টেমে প্রিন্ট ও সাইনেজ',
    descEn: 'Run wide flex printing, acrylic CNC laser cutting, LED lettering, and metal welding in one invoice.',
    descBn: 'ডিজিটাল ব্যানার প্রিন্ট, এক্রিলিক লেজার কাটিং ও মেটাল ফ্রেম ওয়েল্ডিং এক ইনভয়েসেই পরিচালনা।',
  },
]

// 9. Bangladesh-Specific Features (Authoritative Status)
export const BANGLADESH_SPECIFIC_FEATURES = [
  {
    titleEn: '৳ BDT Native Currency & South Asian Commas',
    titleBn: 'বাংলাদেশি টাকা ও দেশীয় কমা বিন্যাস',
    descEn: 'Native support for Bangladeshi Taka formatting (e.g. ৳ ১,২৫,০০০) and automatic Bengali number spellout.',
    descBn: 'বাংলাদেশি টাকার সংখ্যা নিয়ম (যেমন ৳ ১,২৫,০০০) এবং ইনভয়েসে স্বয়ংক্রিয় টাকায় রূপান্তর।',
    status: 'Available',
  },
  {
    titleEn: 'Full Bangla + English Interface',
    titleBn: 'সম্পূর্ণ বাংলা ও ইংরেজি ইন্টারফেস',
    descEn: 'Seamlessly toggle between 100% English and 100% Bangla rendered with clean Hind Siliguri typography.',
    descBn: 'মুহূর্তেই শতভাগ বাংলা অথবা শতভাগ ইংরেজি ইন্টারফেসে কাজ করার নির্ভরযোগ্য সুবিধা।',
    status: 'Available',
  },
  {
    titleEn: '64 Districts & Printing Hub Upazilas',
    titleBn: '৬৪ জেলা ও প্রিন্টিং ক্লাস্টার ঠিকানা',
    descEn: 'Built-in database of all 8 divisions, 64 districts, and local industrial clusters (Arambagh, Fakirapool, etc.).',
    descBn: 'বাংলাদেশের ৮ বিভাগ, ৬৪ জেলা ও প্রধান প্রিন্টিং ক্লাস্টার সম্বলিত রেডিমেড ঠিকানা ড্রপডাউন।',
    status: 'Available',
  },
  {
    titleEn: 'NBR VAT, 13-Digit BIN & Mushak 6.3',
    titleBn: 'এনবিআর ভ্যাট, ১৩-সংখ্যার বিআইএন ও মূসক ৬.৩',
    descEn: '13-digit Business Identification Number validation, standard NBR VAT rates, and delivery challans.',
    descBn: '১৩ সংখ্যার বিআইএন ভ্যালিডেশন, এনবিআর নির্ধারিত ভ্যাট হার ও বাণিজ্যিক ডেলিভারি চালান প্রিন্ট।',
    status: 'Available',
  },
  {
    titleEn: 'bKash, Nagad & Rocket MFS Records',
    titleBn: 'বিকাশ, নগদ ও রকেট পেমেন্ট ট্র্যাকিং',
    descEn: 'Record merchant TrxID numbers, split advance tender deposits, and track cash-out charges transparently.',
    descBn: 'পেমেন্ট ট্রানজেকশন আইডি (TrxID) সংরক্ষণ এবং ১ ক্লিকে ক্যাশআউট চার্জ হিসাব সমন্বয়।',
    status: 'Available',
  },
  {
    titleEn: '1-Click WhatsApp Quote & Challan Dispatch',
    titleBn: '১-ক্লিকে হোয়াটসঅ্যাপে চালান ও কোটেশন',
    descEn: 'Send direct branded PDF links and reminder messages to customer WhatsApp without saving numbers.',
    descBn: 'নাম্বার সেভ না করেই গ্রাহকের হোয়াটসঅ্যাপে সরাসরি ব্র্যান্ডেড কোটেশন ও চালান লিংক প্রেরণ।',
    status: 'Available',
  },
  {
    titleEn: 'Traditional Advance & Credit Culture',
    titleBn: 'অগ্রিম বুকিং ও স্থানীয় ক্রেডিট খাতা',
    descEn: 'Structured around local press practices: booking deposit, delivery balance, and 15-day credit settlement.',
    descBn: 'বাস্তব প্রেস কালচার অনুযায়ী বুকিংয়ের সময় অগ্রিম, ডেলিভারিতে জমা এবং নির্দিষ্ট মেয়াদে বাকি খাতা।',
    status: 'Available',
  },
  {
    titleEn: 'Mobile Floor Station on Budget Android',
    titleBn: 'স্মার্টফোনে কারখানা ফ্লোর টার্মিনাল',
    descEn: 'Shop floor managers and press operators can update machine tasks and upload photos on standard phones.',
    descBn: 'যেকোনো সাধারণ অ্যান্ড্রয়েড ফোনেই প্রেস অপারেটররা কাজের অগ্রগতি আপডেট ও ছবি আপলোড করতে পারবেন।',
    status: 'Available',
  },
]

// 12. FAQ Section: 12 Authentic Operational Questions
export const FAQS = [
  {
    qEn: 'What is PrintFlow?',
    qBn: 'প্রিন্টফ্লো (PrintFlow) কী?',
    aEn: 'PrintFlow is business software built specifically for printing presses, digital banner shops, signage fabricators, and advertising workshops in Bangladesh. It connects quotations, orders, design approval, production, inventory, delivery, and accounting in one unified system.',
    aBn: 'প্রিন্টফ্লো হলো বাংলাদেশের ডিজিটাল প্রিন্ট, অফসেট প্রেস, ব্যানার, সাইনবোর্ড ফ্যাব্রিকেশন ও বিজ্ঞাপন এজেন্সির জন্য বিশেষভাবে তৈরি সফটওয়্যার। এটি কোটেশন, অর্ডার, ডিজাইন অনুমোদন, কারখানা প্রোডাকশন, স্টক, চালান ও বকেয়া আদায়ের পুরো ব্যবসাকে এক ছাদের নিচে পরিচালনা করে।',
  },
  {
    qEn: 'Who is PrintFlow for?',
    qBn: 'প্রিন্টফ্লো কাদের জন্য তৈরি?',
    aEn: 'It is built for commercial offset presses, digital flex/banner workshops, acrylic and LED signboard makers, carton packaging plants, sticker printers, steel fabrication teams, and advertising agencies across Bangladesh.',
    aBn: 'এটি বাংলাদেশের কমার্শিয়াল অফসেট প্রেস, ফ্লেক্স/ডিজিটাল ব্যানার শপ, এক্রিলিক ও এলইডি সাইনবোর্ড নির্মাতা, প্যাকেজিং কারখানা, স্টিকার প্রিন্টার এবং অ্যাডভার্টাইজিং এজেন্সির জন্য তৈরি।',
  },
  {
    qEn: 'Can I manage quotations and invoices in square feet (SFT)?',
    qBn: 'স্কয়ারফিট (SFT) অনুযায়ী কি কোটেশন ও ইনভয়েস তৈরি করা যায়?',
    aEn: 'Yes. Enter dimensions in inches, feet, or running feet, and PrintFlow automatically calculates total square footage, applies material and finishing rates, handles minimum billable limits, and formats branded PDF quotes.',
    aBn: 'হ্যাঁ। ইঞ্চি বা ফুটে মাপ লিখলেই সফটওয়্যার স্বয়ংক্রিয়ভাবে স্কয়ারফিট বের করে মেটেরিয়াল রেট ও ফিনিশিং যোগ করে পেশাদার পিডিএফ কোটেশন প্রস্তুত করে দেয়।',
  },
  {
    qEn: 'Can I track production progress on the factory floor?',
    qBn: 'কারখানার ফ্লোরে প্রোডাকশনের অগ্রগতি কি মনিটর করা যায়?',
    aEn: 'Yes. The Production Queue tracks jobs across queued, printing, lamination, die-cutting, fabrication, and ready for delivery. Operators can also update job status directly from their mobile phones.',
    aBn: 'হ্যাঁ। কোন কাজ প্রিন্ট হচ্ছে, কোনটা লেমিনেশনে আছে আর কোনটা ডেলিভারির জন্য রেডি তা সরাসরি মনিটর করা যায়। অপারেটররাও মোবাইল থেকে কাজের স্ট্যাটাস আপডেট করতে পারেন।',
  },
  {
    qEn: 'Can I manage roll inventory and material wastage?',
    qBn: 'ফ্লেক্স রোল এবং কাঁচামালের অপচয় কি ট্র্যাক করা যায়?',
    aEn: 'Yes. PrintFlow tracks master rolls by width and length (e.g. 10ft × 164ft = 1,640 SFT), subtracts square footage as jobs finish, accounts for loading scrap, and alerts you when stocks drop low.',
    aBn: 'হ্যাঁ। প্রতিটি রোলের প্রস্থ ও দৈর্ঘ্য অনুযায়ী স্কয়ারফিটের ব্যবহার ও অপচয় লাইভ কমে যায় এবং স্টক নির্দিষ্ট সীমার নিচে নামলে অ্যালার্ট প্রদান করে।',
  },
  {
    qEn: 'Can I track customer dues and send WhatsApp reminders?',
    qBn: 'গ্রাহকদের বকেয়া খাতা এবং হোয়াটসঅ্যাপে তাগাদা পাঠানো কি সম্ভব?',
    aEn: 'Yes. Track advance booking payments, cash collected on delivery, and overdue balances. With 1-click, you can dispatch polite payment reminder messages with total dues directly to customer WhatsApp.',
    aBn: 'হ্যাঁ। গ্রাহকের আংশিক জমা ও বকেয়া নিখুঁতভাবে রেকর্ড থাকে। মাত্র ১ ক্লিকে গ্রাহকের হোয়াটসঅ্যাপে বকেয়া টাকার ভদ্র রিমাইন্ডার পাঠানো যায়।',
  },
  {
    qEn: 'Does PrintFlow support Bengali language?',
    qBn: 'প্রিন্টফ্লোতে কি বাংলা ভাষা সাপোর্ট করে?',
    aEn: 'Full native support! You can use PrintFlow in 100% pure Bangla (with clear Hind Siliguri typography) or 100% English. Customer names, delivery challans, and money receipts all render properly in Bengali.',
    aBn: 'শতভাগ পরিপূর্ণ বাংলা সাপোর্ট রয়েছে! ‘হিন্দ শিলিগুড়ি’ ফন্টে শুদ্ধ বাংলায় অথবা ইংরেজিতে কাজ করতে পারবেন। গ্রাহকের নাম, ডেলিভারি চালান ও মানি রিসিট বাংলায় প্রিন্ট হয়।',
  },
  {
    qEn: 'Does it support Bangladeshi Taka (৳ BDT)?',
    qBn: 'এটি কি বাংলাদেশি টাকা (৳ BDT) সাপোর্ট করে?',
    aEn: 'Yes. All financial calculations, quotes, invoices, payments, and profit reports natively use Bangladeshi Taka (৳ BDT) with standard South Asian comma separation (e.g. ৳ ১,২৫,০০০).',
    aBn: 'হ্যাঁ। সমস্ত হিসাব, ইনভয়েস, কোটেশন ও মুনাফা সরাসরি বাংলাদেশি টাকা (৳ BDT) এবং দেশীয় কমা বিন্যাসে (যেমন ৳ ১,২৫,০০০) পরিচালিত হয়।',
  },
  {
    qEn: 'Can employees have different responsibilities and access levels?',
    qBn: 'কর্মচারীদের জন্য কি আলাদা অনুমতি ও ভূমিকা নির্ধারণ করা যায়?',
    aEn: 'Yes. Business owners, sales staff, graphic designers, production managers, press operators, and delivery personnel each have role-based permissions showing only what they need to see.',
    aBn: 'হ্যাঁ। ভূমিকাভিত্তিক পারমিশন সিস্টেমের কারণে মালিক, সেলসম্যান, ডিজাইনার, প্রোডাকশন ম্যানেজার ও অপারেটররা যার যার নির্দিষ্ট প্যানেলে নিরাপদভাবে কাজ করতে পারবেন।',
  },
  {
    qEn: 'Can I use PrintFlow on mobile smartphones?',
    qBn: 'প্রিন্টফ্লো কি স্মার্টফোনে ব্যবহার করা যায়?',
    aEn: 'PrintFlow is fully responsive and mobile-friendly. Shop owners can check sales, review customer dues, and monitor production queues from any Android or iPhone without needing a computer.',
    aBn: 'প্রিন্টফ্লো সম্পূর্ণ মোবাইল-ফ্রেন্ডলি। ফলে কম্পিউটার ছাড়াও যেকোনো সাধারণ স্মার্টফোনে লাইভ সেলস, বকেয়া খাতা ও প্রোডাকশন মনিটর করা যায়।',
  },
  {
    qEn: 'Can I start with a free trial?',
    qBn: 'আমি কি ফ্রি ট্রায়াল দিয়ে শুরু করতে পারি?',
    aEn: 'Yes. You can start with our dedicated free evaluation trial without entering any credit card. You get full access to quotations, production tracking, roll inventory, and accounting.',
    aBn: 'হ্যাঁ। কোনো ক্রেডিট কার্ড ছাড়াই আপনি ফ্রি ট্রায়াল দিয়ে শুরু করতে পারেন এবং কোটেশন, প্রোডাকশন, রোল স্টক ও একাউন্টিং মডিউল ব্যবহার করে দেখতে পারেন।',
  },
  {
    qEn: 'How easy is it to move from Excel or paper registers?',
    qBn: 'খাতা বা এক্সেল থেকে প্রিন্টফ্লোতে আসা কতটা সহজ?',
    aEn: 'Very easy. PrintFlow is built around how print shops already operate in Bangladesh. You can import your customer lists and material price lists, and our Dhaka onboarding team provides live walkthrough support.',
    aBn: 'খুবই সহজ। সফটওয়্যারটি বাংলাদেশি প্রেসের কাজের ধরনের সাথে মিল রেখে তৈরি। গ্রাহক তালিকা সহজেই যুক্ত করা যায় এবং আমাদের ঢাকা অনবোর্ডিং টিম লাইভ ডেমো ও সহযোগিতা প্রদান করে।',
  },
]
