import {
  Printer,
  FileSpreadsheet,
  MessageSquare,
  FileText,
  Clock,
  Layers,
  Wrench,
  Truck,
  DollarSign,
  TrendingUp,
  Users,
  ShieldCheck,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Smartphone,
  CreditCard,
  Building2,
  Package,
  Sparkles,
  Search,
  Zap,
  BarChart3,
  Calendar,
  Lock,
  Boxes,
  HelpCircle,
} from 'lucide-react'

export interface NavItem {
  labelEn: string
  labelBn: string
  href: string
}

export const MARKETING_NAV_ITEMS: NavItem[] = [
  { labelEn: 'Features', labelBn: 'বৈশিষ্ট্যসমূহ', href: '/#features' },
  { labelEn: 'How It Works', labelBn: 'কাজের ধাপ', href: '/#how-it-works' },
  { labelEn: 'Solutions', labelBn: 'ইন্ডাস্ট্রি সলিউশন', href: '/#solutions' },
  { labelEn: 'Pricing', labelBn: 'মূল্যতালিকা', href: '/#pricing' },
  { labelEn: 'FAQ', labelBn: 'প্রশ্নোত্তর', href: '/#faq' },
]

export const TRUST_INDICATORS = [
  { icon: Building2, textEn: 'Built for Bangladesh businesses', textBn: 'বাংলাদেশের প্রেস ও সাইনেজ উপযোগী' },
  { icon: DollarSign, textEn: '৳ BDT native support', textBn: '৳ বাংলাদেশি টাকা হিসাব' },
  { icon: Sparkles, textEn: 'বাংলা + English interface', textBn: 'বাংলা + ইংরেজি ইন্টারফেস' },
  { icon: Smartphone, textEn: 'Mobile-first & touch friendly', textBn: 'মোবাইল ও ট্যাবলেট ফ্রেন্ডলি' },
]

// 3. Problem Section: Before vs After
export const PROBLEMS_BEFORE = [
  {
    titleEn: 'Quotes Scattered Across WhatsApp',
    titleBn: 'হোয়াটসঅ্যাপে হারানো কোটেশন',
    descEn: 'Prices quoted in chat messages get lost, leading to billing disputes and lost sales.',
    descBn: 'চ্যাটে দেওয়া কোটেশন হারিয়ে যায়, ফলে বিল করার সময় ভুল বোঝাবুঝি ও অর্ডার হাতছাড়া হয়।',
  },
  {
    titleEn: 'Job Orders Written on Loose Paper',
    titleBn: 'ছেঁড়া কাগজে হাতে লেখা অর্ডার',
    descEn: 'Paper slips get stained by ink, torn, or misplaced on the production floor.',
    descBn: 'কাগজের চিরকুট কালিতে নষ্ট হয়, হারিয়ে যায় বা অপারেটরের কাছে পৌঁছাতে দেরি হয়।',
  },
  {
    titleEn: 'Frequent Production Delays & Misprints',
    titleBn: 'প্রোডাকশনে অযথা বিলম্ব ও ভুল প্রিন্ট',
    descEn: 'No real-time machine queue visibility. Urgent jobs get delayed behind regular orders.',
    descBn: 'মেশিনের কাজের সিরিয়াল স্পষ্ট না থাকায় জরুরি কাজ আটকে যায় এবং ডেলিভারি মিস হয়।',
  },
  {
    titleEn: 'Untracked Material & Ink Wastage',
    titleBn: 'কাঁচামাল ও কালির অজানা অপচয়',
    descEn: 'Flex rolls, vinyl, and solvent inks disappear without proper consumption records.',
    descBn: 'রোল মিডিয়া ও কালির হিসাব না থাকায় প্রতি মাসে বড় অঙ্কের লুকায়িত লোকসান হয়।',
  },
  {
    titleEn: 'Customers Forgetting Outstanding Dues',
    titleBn: 'গ্রাহকদের ভুলে যাওয়া বকেয়া টাকা',
    descEn: 'No automatic payment reminders. Thousands of Taka remain locked in overdue credit.',
    descBn: 'স্বয়ংক্রিয় তাগাদা না থাকায় লাখ লাখ টাকার বিল বকেয়া পড়ে থাকে মাসের পর মাস।',
  },
  {
    titleEn: 'No Clear Idea of Job Profitability',
    titleBn: 'প্রতি অর্ডারে আসল লাভ অজানা',
    descEn: 'Shop owners guess profits without factoring actual media, ink, labor, and transport.',
    descBn: 'মেটেরিয়াল, বিদ্যুৎ ও লেবার খরচ বাদ দিয়ে আসল লাভ কত তা না জেনেই দর নির্ধারণ।',
  },
]

export const SOLUTIONS_AFTER = [
  {
    titleEn: 'Instant Professional Digital Quotations',
    titleBn: 'মুহূর্তে নিখুঁত ডিজিটাল কোটেশন',
    descEn: 'Generate SFT-calculated branded PDF estimates with 1-click WhatsApp dispatch.',
    descBn: 'স্কয়ারফিট হিসাব ও মেটেরিয়াল রেট দিয়ে ১ ক্লিকে হোয়াটসঅ্যাপে পিডিএফ কোটেশন পাঠান।',
  },
  {
    titleEn: 'Centralized Digital Job Tickets',
    titleBn: 'একটি কেন্দ্রীয় ডিজিটাল জব টিকিট',
    descEn: 'Approved quotes automatically convert to production jobs with specs & artwork.',
    descBn: 'কোটেশন অনুমোদন হওয়ামাত্র স্বয়ংক্রিয়ভাবে স্পেসিফিকেশনসহ কারখানার জবে রূপান্তর।',
  },
  {
    titleEn: 'Live Production Kanban & Floor Station',
    titleBn: 'লাইভ প্রোডাকশন কানবান বোর্ড',
    descEn: 'Track jobs across RIP, Print, Lamination, Fabrication, and Delivery in real time.',
    descBn: 'প্রিন্ট, লেমিনেশন, ফ্রেম ও ডেলিভারির প্রতিটি ধাপ স্ক্রিনে রিয়েল-টাইমে মনিটর করুন।',
  },
  {
    titleEn: 'Roll & SqFt Material Inventory',
    titleBn: 'রোল ও স্কয়ারফিট ভিত্তিক স্টক নিয়ন্ত্রণ',
    descEn: 'Deduct exact square footage and wastage dynamically as operators complete jobs.',
    descBn: 'প্রিন্ট শেষ হওয়ামাত্র স্বয়ংক্রিয়ভাবে রোল থেকে স্কয়ারফিট ও অপচয়ের হিসাব সমন্বয়।',
  },
  {
    titleEn: 'Automated WhatsApp & SMS Due Reminders',
    titleBn: 'স্বয়ংক্রিয় হোয়াটসঅ্যাপ ও এসএমএস তাগাদা',
    descEn: 'Track partial payments, cash receipts, and send automated polite due balance reminders.',
    descBn: 'আংশিক পেমেন্ট ও বাকি টাকার হিসাব রাখুন এবং ১ ক্লিকে গ্রাহককে রিমাইন্ডার পাঠান।',
  },
  {
    titleEn: 'True Job Costing & Net Profit Analytics',
    titleBn: 'প্রতিটি অর্ডারে আসল নেট মুনাফা নির্ণয়',
    descEn: 'See exact margins by deducting media cost, operator time, framing, and logistics.',
    descBn: 'কালি, মিডিয়া, কারিগর ও পরিবহন খরচ বাদ দিয়ে প্রতিটা কাজের খাঁটি লাভ জেনে নিন।',
  },
]

// 4. Solution Section: 9 Core Pillars
export const CORE_FEATURES = [
  {
    icon: FileText,
    titleEn: 'Sales & Quotations',
    titleBn: 'কোটেশন ও সেলস ম্যানেজমেন্ট',
    descEn: 'Create professional quotations quickly with measurements (inch/ft/sft), materials, finishing add-ons, VAT, and discounts.',
    descBn: 'ইঞ্চি/ফুট/স্কয়ারফিট পরিমাপ, মেটেরিয়াল, ফিনিশিং ও ভ্যাটসহ নিখুঁত বাণিজ্যিক কোটেশন তৈরি করুন কয়েক সেকেন্ডে।',
    tagEn: 'SFT Auto-Calculator',
    tagBn: 'স্বয়ংক্রিয় এসএফটি হিসাব',
  },
  {
    icon: CheckCircle2,
    titleEn: 'Order Management',
    titleBn: 'স্মার্ট অর্ডার ট্র্যাকিং',
    descEn: 'Turn approved quotations into verified orders, generate sequential job numbers, and dispatch automatic customer confirmations.',
    descBn: 'কোটেশন গৃহীত হলে ১ ক্লিকে অর্ডার কনফার্ম করুন, ধারাবাহিক নম্বর দিন এবং গ্রাহককে নিশ্চিতকরণ জানান।',
    tagEn: 'One-Click Conversion',
    tagBn: '১-ক্লিকে অর্ডার রূপান্তর',
  },
  {
    icon: Printer,
    titleEn: 'Production Floor Kanban',
    titleBn: 'কারখানা প্রোডাকশন কানবান',
    descEn: 'Visual drag-and-drop workflow tracking pre-press artwork proofing, large-format printing, lamination, CNC die-cutting, and assembly.',
    descBn: 'ডিজাইন প্রুফিং, লার্জ ফরম্যাট প্রিন্টিং, লেমিনেশন, কাটিং এবং অ্যাসেম্বলির নিখুঁত ভিজ্যুয়াল মনিটরিং।',
    tagEn: 'Live Floor Queue',
    tagBn: 'লাইভ মেশিন লাইন',
  },
  {
    icon: Boxes,
    titleEn: 'Inventory & Roll Tracker',
    titleBn: 'ইনভেন্টরি ও রোল ট্র্যাকার',
    descEn: 'Track flex, vinyl, backlit, canvas rolls, acrylic sheets, PVC foam boards, LED modules, power supplies, and solvent inks in real time.',
    descBn: 'স্টার ফ্লেক্স, ভিনাইল রোল, এক্রিলিক শিট, পিভিসি বোর্ড, এলইডি লাইট এবং কালির স্টক ও অবশিষ্ট স্কয়ারফিট ট্র্যাকিং।',
    tagEn: 'Roll Yield & Wastage',
    tagBn: 'রোল ওয়েস্টেজ ট্র্যাকিং',
  },
  {
    icon: CreditCard,
    titleEn: 'Payments & Due Recovery',
    titleBn: 'পেমেন্ট ও বকেয়া আদায়',
    descEn: 'Manage cash in hand, bKash/Nagad MFS, bank transfers, partial advance deposits, and overdue receivable aging buckets.',
    descBn: 'নগদ ক্যাশ, বিকাশ/নগদ, ব্যাংক ট্রান্সফার, অগ্রিম জমা এবং গ্রাহকদের বকেয়ার বয়স অনুযায়ী ক্যাটাগরি ব্যবস্থাপনা।',
    tagEn: 'Multi-Tender Split',
    tagBn: 'মাল্টি-মেথড পেমেন্ট',
  },
  {
    icon: TrendingUp,
    titleEn: 'Job Profitability & Costing',
    titleBn: 'জব কস্টিং ও নিট মুনাফা',
    descEn: 'Know your exact bill of materials (BOM), machine run-time cost, operator labor, framing hardware, transport, and real net profit.',
    descBn: 'মেটেরিয়াল, বিদ্যুৎ, মেশিন অপচয়, কারিগর ও পরিবহন খরচ সমন্বয় করে প্রতি অর্ডারে আসল মুনাফা নিশ্চিত করুন।',
    tagEn: 'Stop Guessing Profit',
    tagBn: 'মুনাফা অনুমান নয়, নিশ্চিত',
  },
  {
    icon: Truck,
    titleEn: 'Delivery & Site Installation',
    titleBn: 'ডেলিভারি চালান ও ইনস্টলেশন',
    descEn: 'Issue NBR-compliant Delivery Challans, assign field fitting teams, capture site completion photos, and collect customer signatures.',
    descBn: 'এনবিআর স্বীকৃত চালান প্রিন্ট করুন, অন-সাইট ফিটার টিম পাঠান এবং ইনস্টলেশন সাইট ফটোর মাধ্যমে ডেলিভারি প্রমাণ রাখুন।',
    tagEn: 'Proof of Delivery',
    tagBn: 'অন-সাইট সাইন ও ছবি',
  },
  {
    icon: Users,
    titleEn: 'HR, Attendance & Payroll',
    titleBn: 'কর্মী হাজিরা ও পে-রোল',
    descEn: 'Track press operator shifts, daily attendance, overtime hours with double-rate rules, salary advances, and monthly pay-slips.',
    descBn: 'মেশিন অপারেটর ও কর্মীদের শিফট হাজিরা, ওভারটাইম হিসাব, অগ্রিম বেতন সমন্বয় এবং ১ ক্লিকে পে-রোল তৈরি।',
    tagEn: 'Bangladesh Labor Law',
    tagBn: 'শ্রম আইন অনুযায়ী হিসাব',
  },
  {
    icon: BarChart3,
    titleEn: 'Executive BI Reports',
    titleBn: 'বিজনেস ইন্টেলিজেন্স ও অডিট',
    descEn: 'Actionable executive dashboards for daily sales collection, expense breakdown, VAT Mushak 6.3 summaries, and customer ledger audits.',
    descBn: 'দৈনিক সেলস কালেকশন, খরচের খাতওয়ারি বিশ্লেষণ, মূসক ৬.৩ ভ্যাট রিটার্ন এবং গ্রাহক লেজার রিপোর্ট এক পলকে।',
    tagEn: 'Exportable to Excel',
    tagBn: 'এক্সেলে এক্সপোর্ট সুবিধা',
  },
]

// 5. How It Works Pipeline
export const WORKFLOW_STEPS = [
  { step: '01', titleEn: 'Customer Request', titleBn: 'গ্রাহকের চাহিদা', descEn: 'Receive inquiry with dimensions & material specifications.', descBn: 'গ্রাহকের কাছ থেকে মাপ ও মেটেরিয়ালের চাহিদা গ্রহণ।' },
  { step: '02', titleEn: 'Quotation Created', titleBn: 'কোটেশন তৈরি', descEn: 'Automated SFT rate, finishing add-ons, and VAT calculated.', descBn: 'স্বয়ংক্রিয় স্কয়ারফিট রেট, ফিনিশিং ও ভ্যাটসহ প্রফেশনাল এস্টিমেট।' },
  { step: '03', titleEn: 'Customer Approval', titleBn: 'গ্রাহকের সম্মতি', descEn: 'Quote approved via WhatsApp or email with advance deposit.', descBn: 'হোয়াটসঅ্যাপে কোটেশন পাঠিয়ে অগ্রিম পেমেন্টসহ অর্ডার অনুমোদন।' },
  { step: '04', titleEn: 'Order Confirmed', titleBn: 'অর্ডার বুকিং', descEn: 'Converts to job order with guaranteed sequential ID.', descBn: 'অনুমোদিত কোটেশন স্বয়ংক্রিয়ভাবে জব অর্ডারে রূপান্তর।' },
  { step: '05', titleEn: 'Design Proofing', titleBn: 'ডিজাইন ও প্রুফিং', descEn: 'Designer uploads artwork preview for client digital signoff.', descBn: 'গ্রাফিক ডিজাইনারের ফাইনাল আর্টওয়ার্ক প্রুফিং ও গ্রাহকের সাইন।' },
  { step: '06', titleEn: 'Press Production', titleBn: 'মেশিন প্রিন্টিং', descEn: 'Operators load roll media and print with zero spec ambiguity.', descBn: 'অপারেটর স্পেসিফিকেশন দেখে সরাসরি মেশিনে প্রিন্ট সম্পন্ন করেন।' },
  { step: '07', titleEn: 'Finishing & QC', titleBn: 'ফিনিশিং ও কোয়ালিটি', descEn: 'Lamination, eyelet grommets, hem sewing, and quality check.', descBn: 'লেমিনেশন, কাটিং, আইলেট রিং ও কোয়ালিটি চেকিং সম্পন্ন।' },
  { step: '08', titleEn: 'Challan & Delivery', titleBn: 'চালান ও ডেলিভারি', descEn: 'Generated delivery challan and dispatch tracking.', descBn: 'এনবিআর ডেলিভারি চালান সহ মালামাল গ্রাহকের গন্তব্যে পাঠানো।' },
  { step: '09', titleEn: 'Site Installation', titleBn: 'সাইট ইনস্টলেশন', descEn: 'Signboard or billboard erected with completion proof photo.', descBn: 'সাইট টেকনিশিয়ান দ্বারা সাইনবোর্ড স্থাপন ও ছবি আপলোড।' },
  { step: '10', titleEn: 'Final Due Collection', titleBn: 'বকেয়া বিল আদায়', descEn: 'Collect balance amount via Cash or bKash/Nagad.', descBn: 'বাকি টাকা ক্যাশ বা মোবাইল ব্যাংকিংয়ের মাধ্যমে আদায়।' },
  { step: '11', titleEn: 'Profit Realized', titleBn: 'নিট মুনাফা নিশ্চিত', descEn: 'Actual job profit and material consumption locked in ledger.', descBn: 'প্রকৃত খরচ ও কালেকশন সমন্বয় করে নিখুঁত নিট লাভ লেজারে রেকর্ড।' },
]

// 6. Industry Solutions
export const INDUSTRY_SOLUTIONS = [
  {
    id: 'digital_print',
    titleEn: 'Digital Printing Presses',
    titleBn: 'ডিজিটাল প্রিন্টিং প্রেস',
    descEn: 'For short-run commercial printers producing posters, brochures, visiting cards, flyers, and certificates with fast turnover.',
    descBn: 'ভিজিটিং কার্ড, ব্রোশার, পোস্টার ও লিফলেট প্রিন্টারদের দ্রুত বুকিং, পেপার হিসাব ও ডেলিভারি নিশ্চিত করতে।',
    highlightEn: 'Paper Sheet Weight & CTP plate tracking',
    highlightBn: 'কাগজের রিম, ওজন ও প্লেট ট্র্যাকিং',
  },
  {
    id: 'offset_press',
    titleEn: 'Offset Printing Houses',
    titleBn: 'অফসেট প্রিন্টিং কারখানা',
    descEn: 'Manage multi-color Heidelberg/Komori runs, paper cutting, plate exposing, ink mixing, book-binding, and packaging box die-punching.',
    descBn: 'মাল্টিকালর অফসেট প্রেস, কাগজ কাটিং, প্লেট মেকিং, বই বাইন্ডিং ও প্যাকেট ডাই-কাটিংয়ের পূর্ণাঙ্গ অটোমেশন।',
    highlightEn: 'Sheet yield & multi-up nesting',
    highlightBn: 'শিট ইয়েল্ড ও মাল্টি-আপ নেস্টিং',
  },
  {
    id: 'flex_banner',
    titleEn: 'Flex & Banner Workshops',
    titleBn: 'ফ্লেক্স ও ব্যানার কারখানা',
    descEn: 'Large-format wide solvent printing, Star Flex, Chinese flex, backlit fabric, canvas, eyelet ring punching, and hem welding.',
    descBn: '১০/১২ ফিট লার্জ ফরম্যাট সলভেন্ট প্রিন্টিং, স্টার ফ্লেক্স, ব্যাকলিট কাপড়, আইলেট ড্রিলিং ও রড ওয়েল্ডিং।',
    highlightEn: 'Roll square-footage & loading scrap',
    highlightBn: 'রোল স্কয়ারফিট ও লোডিং অপচয় ট্র্যাকিং',
  },
  {
    id: 'sticker_print',
    titleEn: 'Sticker & Label Printers',
    titleBn: 'স্টিকার ও লেবেল প্রিন্টিং',
    descEn: 'Vinyl decals, clear stickers, barcode labels, kiss-cut roll labels, reflective vinyl, and gloss/matte lamination jobs.',
    descBn: 'ভিনাইল স্টিকার, ডাই-কাট লেবেল, স্বচ্ছ স্টিকার, রিফ্লেক্টিভ শিট ও ম্যাট/গ্লস লেমিনেশন ব্যবস্থাপনা।',
    highlightEn: 'Plotter kiss-cut & lamination rates',
    highlightBn: 'প্লটার কাটিং ও লেমিনেশন রেট',
  },
  {
    id: 'packaging',
    titleEn: 'Carton & Packaging Hubs',
    titleBn: 'কার্টন ও প্যাকেজিং ইন্ডাস্ট্রি',
    descEn: 'Duplex board cartons, garment master cartons, food packaging boxes, spot UV, foil stamping, and pasting lines.',
    descBn: 'ডুপ্লেক্স বোর্ড কার্টন, গার্মেন্টস বক্স, ফুড প্যাকেজিং, স্পট ইউভি, ফয়েল প্রিন্ট ও পেস্টিং লাইন নিয়ন্ত্রণ।',
    highlightEn: 'GSM sheet calculation & Die charge',
    highlightBn: 'জিএসএম শিট হিসাব ও ডাই চার্জ',
  },
  {
    id: 'signage',
    titleEn: 'Commercial Signage Makers',
    titleBn: 'কমার্শিয়াল সাইনেজ ও নিয়ন',
    descEn: 'Panaflex light boxes, shop fascias, safety signs, wayfinding directional boards, and 3D outdoor signs.',
    descBn: 'প্যানাফ্লেক্স লাইটবক্স, দোকান ফ্রন্ট সাইনেজ, দিকনির্দেশনা বোর্ড এবং বহিরাঙ্গন ৩ডি সাইন।',
    highlightEn: 'RFT frame perimeter calculation',
    highlightBn: 'রানিং ফিট ফ্রেম ও পাইপ হিসাব',
  },
  {
    id: 'acrylic_sign',
    titleEn: 'Acrylic Signage & Laser Studios',
    titleBn: 'এক্রিলিক লেটার ও লেজার স্টুডিও',
    descEn: 'Laser-cut acrylic letters, crystal edge signs, LED channel letters, architectural directory plates, and decorative display panels.',
    descBn: 'লেজার কাট এক্রিলিক বর্ণ, ক্রিস্টাল সাইন, এলইডি ব্যাকলিট চ্যানেল লেটার ও ইন্টারিয়র ডিসপ্লে বোর্ড।',
    highlightEn: 'Sheet thickness (2mm-15mm) pricing',
    highlightBn: 'শিটের পুরুত্ব অনুযায়ী স্বয়ংক্রিয় রেট',
  },
  {
    id: 'led_signboard',
    titleEn: 'LED Signboard & Video Walls',
    titleBn: 'এলইডি সাইনবোর্ড ও ডিজিটাল ডিসপ্লে',
    descEn: 'Single-color scrolling boards, P10/P4 outdoor LED video screens, channel power supplies, and control card programming.',
    descBn: 'পি১০ এলইডি মুভিং ডিসপ্লে, ফুল কালার ভিডিও ওয়াল, পাওয়ার সাপ্লাই ও ড্রাইভার সার্কিট ব্যবস্থাপনা।',
    highlightEn: 'Module count & ampere power budgeting',
    highlightBn: 'মডিউল সংখ্যা ও পাওয়ার ওয়াটেজ হিসাব',
  },
  {
    id: 'metal_fabrication',
    titleEn: 'Metal & Steel Fabrication',
    titleBn: 'মেটাল ও এমএস ফ্রেম ফ্যাব্রিকেশন',
    descEn: 'MS angle frames, square pipe welding, stainless steel golden letters, ACP board cladding, and heavy billboard structures.',
    descBn: 'এমএস এঙ্গেল ফ্রেম, এসএস গোল্ডেন লেটার, এসিপি বোর্ড ক্ল্যাডিং ও ভারী মেটাল বিলবোর্ড কাঠামো।',
    highlightEn: 'Weight (kg) & welding labor costing',
    highlightBn: 'কেজি ওজন ও ওয়েল্ডিং লেবার খরচ',
  },
  {
    id: 'ad_agency',
    titleEn: 'Advertising & Event Agencies',
    titleBn: 'অ্যাডভার্টাইজিং ও ইভেন্ট এজেন্সি',
    descEn: 'Manage nationwide branding campaigns, fair booth stalls, retail kiosk displays, and outsourced press vendor networks.',
    descBn: 'দেশব্যাপী ব্র্যান্ডিং ক্যাম্পেইন, মেলা স্টল ফ্যাব্রিকেশন এবং থার্ড-পার্টি প্রিন্ট ভেন্ডর কোঅর্ডিনেশন।',
    highlightEn: 'Vendor outsourced cost & client markup',
    highlightBn: 'ভেন্ডর আউটসোর্স ও ক্লায়েন্ট মার্কআপ',
  },
  {
    id: 'installation_teams',
    titleEn: 'Installation & Fitting Specialists',
    titleBn: 'ইনস্টলেশন ও ফিটিং কন্ট্রাক্টর',
    descEn: 'Field technician routing, night highway hoarding fixing, scaffolding safety, crane rent, and site completion audit.',
    descBn: 'ফিল্ড টেকনিশিয়ান বরাদ্দ, হাইওয়ে বিলবোর্ড ফিটিং, ক্রেন ভাড়া ও সাইট অডিট ফটো ক্যাপচার।',
    highlightEn: 'Site photo upload & client signoff',
    highlightBn: 'সাইট ফটো প্রমাণ ও মোবাইল সাইন',
  },
  {
    id: 'hybrid_business',
    titleEn: 'Hybrid Print-Signage-Agency',
    titleBn: 'হাইব্রিড প্রেস ও সাইনেজ হাব',
    descEn: 'For versatile modern enterprises operating in-house press, fabrication workshop, and full-service brand execution.',
    descBn: 'যাদের নিজস্ব প্রেস, মেটাল কারখানা এবং বিজ্ঞাপন এজেন্সি সেবা একই সাথে পরিচালিত হয়।',
    highlightEn: 'Unified inter-departmental accounting',
    highlightBn: 'এক ছাদের নিচে সব ডিপার্টমেন্ট সমন্বয়',
  },
]

// 8. Bangladesh Specific Features
export const BANGLADESH_FEATURES = [
  {
    titleEn: '৳ BDT Native Currency & Words',
    titleBn: '৳ বাংলাদেশি টাকা ও কথায় লেখা',
    descEn: 'Native support for Bangladeshi Taka formatting, comma conventions (e.g. ৳ ১,২৫,০০০), and automatic "কথায়" spellout.',
    descBn: 'বাংলাদেশি টাকার সংখ্যা নিয়ম (যেমন ৳ ১,২৫,০০০) এবং চালানে স্বয়ংক্রিয় বাংলায় টাকায় রূপান্তর।',
  },
  {
    titleEn: 'Bangla & English Dual Language Interface',
    titleBn: 'বাংলা ও ইংরেজি ইন্টারফেস',
    descEn: 'Seamless interface switchable on the fly between 100% English and 100% Bangla with Hind Siliguri typography.',
    descBn: 'প্রয়োজন অনুযায়ী মুহূর্তেই শতভাগ বাংলা অথবা শতভাগ ইংরেজি ইন্টারফেসে কাজের সুবিধা।',
  },
  {
    titleEn: 'Bengali Customer & Business Names',
    titleBn: 'বাংলায় গ্রাহক ও প্রতিষ্ঠানের নাম',
    descEn: 'Store customer names, company titles, and job descriptions in pure Bengali without character corruption or font clipping.',
    descBn: 'কোনো ফন্ট ভাঙা বা অস্পষ্টতা ছাড়া বাংলায় গ্রাহকের নাম, দোকান নাম ও কাজের বর্ণনা সংরক্ষণ।',
  },
  {
    titleEn: '64 Districts & Upazila Address Engine',
    titleBn: '৬৪ জেলা ও থানা ভিত্তিক ঠিকানা ড্রপডাউন',
    descEn: 'Built-in database of all 8 divisions, 64 districts, and key printing industrial upazilas across Bangladesh for precise billing.',
    descBn: 'বাংলাদেশের ৮ বিভাগ, ৬৪ জেলা ও গুরুত্বপূর্ণ থানা সম্বলিত রেডিমেড ড্রপডাউন ঠিকানা নির্বাচন।',
  },
  {
    titleEn: 'NBR VAT, 13-Digit BIN & Mushak 6.3',
    titleBn: 'এনবিআর ভ্যাট, ১৩-সংখ্যার বিআইএন ও মূসক ৬.৩',
    descEn: '13-digit Business Identification Number (BIN) validation, standard 15% / 7.5% / 5% NBR rates, and Mushak 6.3 tax invoices.',
    descBn: '১৩ সংখ্যার বিআইএন ভ্যালিডেশন, এনবিআর নির্ধারিত ভ্যাট হার ও মূসক ৬.৩ চালান প্রিন্টিং সুবিধা।',
  },
  {
    titleEn: 'Cash, Partial Deposits & Multi-Tender',
    titleBn: 'নগদ ক্যাশ, আংশিক অগ্রিম ও বাকি খাতা',
    descEn: 'Mirror the real Bangladeshi business culture: 40% advance cash deposit on booking, 30% on delivery, and 30% 15-day credit.',
    descBn: 'বাস্তব প্রেস কালচার অনুযায়ী বুকিংয়ের সময় ৪০% ক্যাশ, ডেলিভারিতে ৩০% এবং বাকি ৩০% নির্দিষ্ট মেয়াদে হিসাব।',
  },
  {
    titleEn: 'bKash, Nagad & Rocket MFS Architecture',
    titleBn: 'বিকাশ, নগদ ও রকেট এমএফএস পেমেন্ট',
    descEn: 'Record merchant TrxID numbers, payment gateway links, and calculate MFS cash-out charges transparently.',
    descBn: 'মার্চেন্ট পেমেন্ট ট্রানজেকশন আইডি (TrxID) সংরক্ষণ এবং ১ ক্লিকে ক্যাশআউট চার্জ হিসাব।',
  },
  {
    titleEn: '1-Click WhatsApp Challan & Quote Dispatch',
    titleBn: '১-ক্লিকে হোয়াটসঅ্যাপে চালান ও কোটেশন',
    descEn: 'Send direct branded PDF links and polite reminder text messages directly to the client’s WhatsApp without saving their number.',
    descBn: 'নাম্বার সেভ না করেই গ্রাহকের হোয়াটসঅ্যাপে সরাসরি ব্র্যান্ডেড পিডিএফ কোটেশন ও চালান প্রেরণ।',
  },
  {
    titleEn: 'Mobile-First Workshop Floor Terminal',
    titleBn: 'স্মার্টফোন ফ্রেন্ডলি কারখানা টার্মিনাল',
    descEn: 'Floor managers and press operators can update machine progress, upload photos, and complete jobs directly on budget Android phones.',
    descBn: 'কমদামী অ্যান্ড্রয়েড ফোনেই প্রেস অপারেটররা কাজের অগ্রগতি আপডেট ও ছবি আপলোড করতে পারবেন।',
  },
  {
    titleEn: 'Offline-Friendly Order Drafts',
    titleBn: 'ইন্টারনেট ড্রপ হলে অফলাইন ড্রাফট সেভ',
    descEn: 'Never lose a customer quotation during Dhaka or district internet outages; offline queue syncs automatically on reconnection.',
    descBn: 'ইন্টারনেট চলে গেলেও কোটেশন তৈরি করা যাবে; নেট সংযোগ আসামাত্র স্বয়ংক্রিয়ভাবে ক্লাউডে সিঙ্ক হবে।',
  },
  {
    titleEn: 'Traditional Commercial Documents',
    titleBn: 'বাণিজ্যিক চালান, মানি রিসিট ও বিলবই',
    descEn: 'Print formatted traditional A4/Half-A4 Challans, Money Receipts, Gate Passes, and Cash Memos for local auditing.',
    descBn: 'প্রিন্ট শপের প্রচলিত এ৪/হাফ-এ৪ ডেলিভারি চালান, মানি রিসিট, গেট পাস ও ক্যাশ মেমো প্রিন্ট।',
  },
]

// 10. Role-Based Details
export const ROLE_DETAILS = [
  {
    id: 'owner',
    titleEn: 'Business Owner',
    titleBn: 'ব্যবসায়ের মালিক / স্বত্বাধিকারী',
    badgeEn: 'Full Executive Vision',
    badgeBn: 'সম্পূর্ণ নির্বাহী নজরদারি',
    metrics: [
      { labelEn: "Today's Sales", labelBn: 'আজকের বিক্রি', value: '৳ 64,800' },
      { labelEn: 'Cash in Hand', labelBn: 'হাতে নগদ ক্যাশ', value: '৳ 32,500' },
      { labelEn: 'Total Customer Due', labelBn: 'মোট গ্রাহক বকেয়া', value: '৳ 1,48,000' },
      { labelEn: 'Estimated Net Profit', labelBn: 'আনুমানিক নিট লাভ', value: '৳ 21,400' },
    ],
    dutiesEn: [
      'Real-time P&L visibility without calling the accountant',
      'One-click approval for high-value quotes and special discounts',
      'Oversee press productivity, machine bottlenecks & roll inventory',
      'Audit customer credit limits before releasing large production runs',
    ],
    dutiesBn: [
      'অ্যাকাউন্ট্যান্টকে না ডেকেও মোবাইলেই আজকের আয়-ব্যয় ও আসল লাভের চিত্র',
      'বড় অঙ্কের কোটেশন ও বিশেষ ছাড়ের ক্ষেত্রে তাৎক্ষণিক মালিকানাধীন অনুমোদন',
      'কারখানার মেশিন উৎপাদনশীলতা, কাজের জটলা ও কাঁচামাল স্টক পর্যবেক্ষণ',
      'বড় অর্ডার ডেলিভারির আগে গ্রাহকের বকেয়া ক্রেডিট লিমিট যাচাই সুবিধা',
    ],
  },
  {
    id: 'sales',
    titleEn: 'Sales Manager',
    titleBn: 'সেলস ও কাস্টমার ম্যানেজার',
    badgeEn: 'Quotes & Clients',
    badgeBn: 'কোটেশন ও গ্রাহক খাতা',
    metrics: [
      { labelEn: 'Pending Quotes', labelBn: 'অপেক্ষমাণ কোটেশন', value: '7 Active' },
      { labelEn: 'Converted Orders', labelBn: 'অর্ডারে রূপান্তর', value: '18 Today' },
      { labelEn: 'Advance Collected', labelBn: 'আদায়কৃত অগ্রিম', value: '৳ 45,000' },
      { labelEn: 'Customer Balance', labelBn: 'বকেয়া তাগাদা তালিকা', value: '12 Due' },
    ],
    dutiesEn: [
      'Calculate multi-item SFT quotations in 60 seconds with material pricing',
      'Instant branded PDF generation with 1-click WhatsApp dispatch',
      'Convert approved estimates into official orders with automatic sequential IDs',
      'Manage CRM contact history, branch records, and overdue balances',
    ],
    dutiesBn: [
      'স্কয়ারফিট মেজারমেন্ট দিয়ে ১ মিনিটে নির্ভুল মেটেরিয়াল কোটেশন প্রস্তুতকরণ',
      'মুহূর্তেই প্রতিষ্ঠানের লোগোসহ পিডিএফ তৈরি এবং হোয়াটসঅ্যাপে ক্লায়েন্টকে প্রেরণ',
      'অনুমোদিত এস্টিমেটকে স্বয়ংক্রিয় সিরিয়াল নম্বরসহ মূল অর্ডারে রূপান্তর',
      'গ্রাহকের পূর্বের কাজের ইতিহাস, স্পেশাল রেট ও বাকি টাকার পূর্ণাঙ্গ সিআরএম',
    ],
  },
  {
    id: 'designer',
    titleEn: 'Pre-Press Graphic Designer',
    titleBn: 'প্রি-প্রেস গ্রাফিক ডিজাইনার',
    badgeEn: 'Artworks & Proofs',
    badgeBn: 'আর্টওয়ার্ক ও প্রুফিং',
    metrics: [
      { labelEn: 'Design Queue', labelBn: 'ডিজাইন কিউ', value: '5 Pending' },
      { labelEn: 'Client Approvals', labelBn: 'অনুমোদনের অপেক্ষায়', value: '3 Waiting' },
      { labelEn: 'Ready for RIP', labelBn: 'প্রিন্টের জন্য রেডি', value: '9 Files' },
      { labelEn: 'Revisions', labelBn: 'সংশোধন অনুরোধ', value: '2 Reworks' },
    ],
    dutiesEn: [
      'Access exact dimensions, bleed, resolution, and client copy without chasing sales',
      'Upload low-res watermarked proofs for digital client signoff before printing',
      'Attach high-res print-ready TIFF/PDF files directly to the job ticket',
      'Eliminate costly misprints caused by outdated WhatsApp file attachments',
    ],
    dutiesBn: [
      'সেলস টিমের পেছনে না ঘুরেও জব টিকেট থেকে সঠিক মাপ, ব্লিড ও টেক্সট প্রাপ্তি',
      'প্রিন্ট করার পূর্বে গ্রাহকের অনুমোদনের জন্য ওয়াটারমার্কযুক্ত ডিজিটাল প্রুফ আপলোড',
      'হাই-রেজুলেশন প্রিন্ট রেডি টিফ/পিডিএফ ফাইল সরাসরি জব টিকেটে সংরক্ষণ',
      'হোয়াটসঅ্যাপে পুরোনো ফাইল প্রিন্ট হয়ে যাওয়া জনিত হাজার টাকার লোকসান রোধ',
    ],
  },
  {
    id: 'production',
    titleEn: 'Production Manager',
    titleBn: 'প্রোডাকশন ও ফ্লোর ইনচার্জ',
    badgeEn: 'Floor Control',
    badgeBn: 'ফ্লোর ও মেশিন শিডিউল',
    metrics: [
      { labelEn: 'Active Print Jobs', labelBn: 'চলমান প্রিন্ট কাজ', value: '11 Jobs' },
      { labelEn: 'In Finishing', labelBn: 'ফিনিশিং চলছে', value: '6 Items' },
      { labelEn: 'Low Media Alerts', labelBn: 'মিডিয়া স্টক ঘাটতি', value: '2 Rolls' },
      { labelEn: 'Wastage Rate', labelBn: 'গড় ওয়েস্টেজ হার', value: '2.4%' },
    ],
    dutiesEn: [
      'Visual drag-and-drop Kanban organizing RIP, Print, Lamination, Die-cut, and Frame',
      'Assign specific operators and machines (Roland, Flora, Konica, CNC, Laser)',
      'Track real-time roll consumption and loading scrap per print run',
      'Log and analyze any production rework, material fault, or machine stoppage',
    ],
    dutiesBn: [
      'কানবান বোর্ডে প্রিন্ট, লেমিনেশন, ডাই-কাট ও ফ্রেম তৈরির কাজ সুবিন্যস্তকরণ',
      'নির্দিষ্ট মেশিনে ও কারিগরের নামে কাজ বরাদ্দ ও শিফট শিডিউলিং',
      'রোল লোডিং ওয়েস্টেজ ও প্রিন্ট মেটেরিয়ালের লাইভ ব্যবহার নিরীক্ষণ',
      'কোনো প্রিন্ট নষ্ট হলে রিওয়ার্ক কারণ ও অতিরিক্ত খরচ তাৎক্ষণিক রেকর্ড',
    ],
  },
  {
    id: 'operator',
    titleEn: 'Print Machine Operator',
    titleBn: 'মেশিন অপারেটর',
    badgeEn: 'Touch Terminal',
    badgeBn: 'টাচ স্টেশন',
    metrics: [
      { labelEn: 'Assigned Today', labelBn: 'আজকের কাজ', value: '6 Jobs' },
      { labelEn: 'In Progress', labelBn: 'মেশিনে রানিং', value: '1 Job' },
      { labelEn: 'Completed', labelBn: 'সম্পন্ন হয়েছে', value: '5 Jobs' },
      { labelEn: 'SFT Output', labelBn: 'মোট প্রিন্ট এসএফটি', value: '1,420 SFT' },
    ],
    dutiesEn: [
      'Simplified big-button mobile touch screen optimized for gloved or ink-stained hands',
      'Click "Start Job" and "Mark Completed" with auto-timestamping',
      'View exact media roll code (e.g. Star Flex 10ft 380gsm) and finishing checklist',
      'Report media tear or ink run-out with a single tap to alert floor manager',
    ],
    dutiesBn: [
      'কালি লাগা হাতে ব্যবহারের উপযোগী সহজ বড় বাটনযুক্ত মোবাইল টাচ ইন্টারফেস',
      'ক্লিক করে কাজ "শুরু" এবং "শেষ" করা—অটোমেটিক সময় রেকর্ড সুবিধা',
      'কোন রোল লাগাতে হবে (যেমন: স্টার ফ্লেক্স ১০ ফিট ৩৮০ জিএসএম) পরিষ্কার নির্দেশনা',
      'কালি শেষ বা মিডিয়া ছিঁড়ে গেলে ১ ট্যাপে সুপারভাইজারকে অ্যালার্ট প্রদান',
    ],
  },
  {
    id: 'staff',
    titleEn: 'Delivery & General Staff',
    titleBn: 'ডেলিভারি ও সাধারণ কর্মী',
    badgeEn: 'Field & Logistics',
    badgeBn: 'মাঠপর্যায় ও লজিস্টিকস',
    metrics: [
      { labelEn: 'Ready for Dispatch', labelBn: 'ডেলিভারি রেডি', value: '8 Challans' },
      { labelEn: 'Out for Delivery', labelBn: 'রাস্তায় আছে', value: '3 Runs' },
      { labelEn: 'Installed Today', labelBn: 'ইনস্টল সম্পন্ন', value: '2 Sites' },
      { labelEn: 'Due Collected', labelBn: 'ক্যাশ আদায়', value: '৳ 18,500' },
    ],
    dutiesEn: [
      'Scan or view delivery challan on mobile with client address and contact button',
      'Capture client signature and snap photo of installed signboard on site',
      'Collect remaining cash or bKash due upon handover and generate money receipt',
      'Auto-update the order status to "Delivered & Settled" instantly',
    ],
    dutiesBn: [
      'মোবাইলেই ডেলিভারি চালান ও ঠিকানার গুগল ম্যাপ বাটন দেখে সাইটে পৌঁছানো',
      'মালামাল বুঝিয়ে দিয়ে সাইনবোর্ডের ছবি ও গ্রাহকের ডিজিটাল স্বাক্ষর গ্রহণ',
      'বাকি টাকা ক্যাশ বা বিকাশে গ্রহণ করে সাথে সাথে গ্রাহককে মানি রিসিট প্রদান',
      'কেন্দ্রীয় সিস্টেমে অটোমেটিক অর্ডার স্ট্যাটাস "ডেলিভার্ড ও পেইড" হিসেবে আপডেট',
    ],
  },
]

// 13. Testimonials (Placeholders representing realistic BD printing hubs)
export const TESTIMONIALS = [
  {
    id: 't-01',
    nameEn: 'Kamrul Hasan',
    nameBn: 'কামরুল হাসান',
    companyEn: 'Padma Digital Press & Signage',
    companyBn: 'পদ্মা ডিজিটাল প্রেস অ্যান্ড সাইনেজ',
    roleEn: 'Managing Director',
    roleBn: 'ম্যানেজিং ডিরেক্টর',
    locationEn: 'Arambagh, Dhaka',
    locationBn: 'আরামবাগ, ঢাকা',
    quoteEn:
      'Before PrintERP, we were losing thousands of Taka every month because of forgotten customer dues and loose paper slips. Now our entire shop runs on one screen — from SFT quotes to machine production and WhatsApp delivery challans.',
    quoteBn:
      'প্রিন্টইআরপি ব্যবহারের আগে প্রতি মাসে বকেয়া বিল ভুলে যাওয়া আর কাগজের স্লিপ নষ্ট হওয়ার কারণে লাখ টাকার ক্ষতি হতো। এখন কোটেশন থেকে শুরু করে মেশিন প্রোডাকশন ও হোয়াটসঅ্যাপ চালান—সবকিছু একটা সিস্টেমেই চোখের পলকে চলে।',
    rating: 5,
    highlightEn: 'Saved ৳85,000+ in uncollected dues within first 60 days',
    highlightBn: 'প্রথম ৬০ দিনেই ৮৫,০০০+ টাকা অনাদায়ী বকেয়া সফলভাবে উদ্ধার',
  },
  {
    id: 't-02',
    nameEn: 'Shariful Islam',
    nameBn: 'শরিফুল ইসলাম',
    companyEn: 'Chittagong Sign & Acrylic Craft',
    companyBn: 'চট্টগ্রাম সাইন অ্যান্ড এক্রিলিক ক্রাফট',
    roleEn: 'Proprietor',
    roleBn: 'স্বত্বাধিকারী',
    locationEn: 'Agrabad, Chattogram',
    locationBn: 'আগ্রাবাদ, চট্টগ্রাম',
    quoteEn:
      'Calculating acrylic letter sizes, LED module counts, and metal frame costs used to take me hours. With PrintERP’s automated pricing and BOM costing, our sales team produces accurate estimates in just 2 minutes.',
    quoteBn:
      'এক্রিলিক লেটার, এলইডি মডিউল আর মেটাল ফ্রেমের হিসাব করতে আগে ঘণ্টার পর ঘণ্টা যেত। প্রিন্টইআরপি-র অটোমেটিক এসএফটি রেটিংয়ের কারণে এখন আমাদের সেলস টিম মাত্র ২ মিনিটেই নিখুঁত এস্টিমেট বানিয়ে গ্রাহককে দিয়ে দেয়।',
    rating: 5,
    highlightEn: 'Quotation turnaround reduced from 3 hours to 2 minutes',
    highlightBn: 'কোটেশন তৈরির সময় ৩ ঘণ্টা থেকে কমে মাত্র ২ মিনিটে নেমেছে',
  },
  {
    id: 't-03',
    nameEn: 'Tariqur Rahman',
    nameBn: 'তারিকুর রহমান',
    companyEn: 'Bengal Pack & Offset Printers',
    companyBn: 'বেঙ্গল প্যাক অ্যান্ড অফসেট প্রিন্টার্স',
    roleEn: 'Production Head',
    roleBn: 'হেড অব প্রোডাকশন',
    locationEn: 'Fakirapool, Dhaka',
    locationBn: 'ফকিরাপুল, ঢাকা',
    quoteEn:
      'The roll inventory tracker is brilliant. It tracks every square foot used on our wide-format printers and alerts us before Star Flex or ink runs out. No more running to the market at 10 PM for emergency media.',
    quoteBn:
      'রোল ইনভেন্টরি ট্র্যাকারটা অসাধারণ। কোন ফ্লেক্স রোল থেকে কত স্কয়ারফিট প্রিন্ট হলো আর কখন স্টক শেষ হবে তা আগেই জানিয়ে দেয়। রাত ১০টায় দৌড়ে গিয়ে জরুরি মেটেরিয়াল কেনার ভোগান্তি চিরতরে বন্ধ হয়েছে।',
    rating: 5,
    highlightEn: 'Zero emergency stockouts on 10ft & 12ft media rolls',
    highlightBn: '১০ ও ১২ ফিট ফ্লেক্স রোলের শূন্য ইমার্জেন্সি স্টকআউট',
  },
]

// 14. FAQ Section: 12 Key Questions
export const FAQS = [
  {
    qEn: 'What is PrintERP?',
    qBn: 'প্রিন্টইআরপি (PrintERP) কী?',
    aEn: 'PrintERP is a specialized cloud ERP software designed specifically for digital printing, offset press, signage, banner fabrication, and advertising businesses in Bangladesh. It connects sales, quotations, pre-press design, machine production, inventory, delivery, and accounting in one cohesive system.',
    aBn: 'প্রিন্টইআরপি হলো বাংলাদেশের ডিজিটাল প্রিন্ট, অফসেট প্রেস, ব্যানার, সাইনবোর্ড ফ্যাব্রিকেশন ও বিজ্ঞাপন এজেন্সির জন্য বিশেষভাবে তৈরি একটি কমপ্লিট ক্লাউড ইআরপি সফটওয়্যার। এটি কোটেশন, ডিজাইন প্রুফিং, মেশিন প্রোডাকশন, স্টক, চালান ও বকেয়া আদায়ের পুরো ব্যবসাকে এক ছাদের নিচে পরিচালনা করে।',
  },
  {
    qEn: 'Who is PrintERP for?',
    qBn: 'প্রিন্টইআরপি কাদের জন্য তৈরি?',
    aEn: 'It is built for commercial printing presses, digital banner shops, acrylic and LED signboard makers, packaging carton manufacturers, sticker/label printers, metal fabrication workshops, and advertising agencies of all sizes across Bangladesh.',
    aBn: 'এটি বাংলাদেশের কমার্শিয়াল প্রিন্টিং প্রেস, ফ্লেক্স/ডিজিটাল ব্যানার শপ, এক্রিলিক ও এলইডি সাইনবোর্ড নির্মাতা, প্যাকেজিং কারখানা, স্টিকার প্রিন্টার এবং অ্যাডভার্টাইজিং এজেন্সির জন্য অত্যন্ত উপযোগী।',
  },
  {
    qEn: 'Can I manage printing and signage together in the same system?',
    qBn: 'আমি কি প্রিন্টিং এবং সাইনেজ ফ্যাব্রিকেশন একসাথে পরিচালনা করতে পারি?',
    aEn: 'Yes! PrintERP uniquely combines multi-department workflows. A single job order can include digital wide flex printing, acrylic CNC laser cutting, LED channel letter wiring, and on-site steel frame installation under unified tracking.',
    aBn: 'হ্যাঁ, অবশ্যই! প্রিন্টইআরপিতে একটি একক অর্ডারের ভেতরেই ডিজিটাল ব্যানার প্রিন্ট, এক্রিলিক লেজার কাটিং, এলইডি লাইটিং এবং অন-সাইট মেটাল ফ্রেম ফিটিংয়ের মতো বহুমুখী ডিপার্টমেন্টাল কাজ সুচারুভাবে ট্র্যাক করা যায়।',
  },
  {
    qEn: 'Does PrintERP support Bengali language?',
    qBn: 'প্রিন্টইআরপিতে কি বাংলা ভাষা সাপোর্ট করে?',
    aEn: 'Full native support! You can use PrintERP in 100% pure Bangla (rendered with the premium Hind Siliguri typography) or 100% English. Customer names, business addresses, delivery challans, and money receipts all render correctly in Bengali without font corruption.',
    aBn: 'শতভাগ পরিপূর্ণ বাংলা সাপোর্ট রয়েছে! প্রিমিয়াম ‘হিন্দ শিলিগুড়ি’ ফন্টে ১০০% শুদ্ধ বাংলায় অথবা ইংরেজিতে কাজ করতে পারবেন। গ্রাহকের নাম, ডেলিভারি চালান ও মানি রিসিট কোনো ফন্ট ভাঙা ছাড়াই চমৎকার বাংলায় প্রিন্ট হয়।',
  },
  {
    qEn: 'Does it support Bangladeshi Taka (৳ BDT)?',
    qBn: 'এটি কি বাংলাদেশি টাকা (৳ BDT) সাপোর্ট করে?',
    aEn: 'Yes. All financial calculations, invoice totals, payments, and quotations default natively to Bangladeshi Taka (৳ BDT) with standard South Asian comma separation (e.g. ৳ ১,২৫,০০০) and automatic Bengali number conversion.',
    aBn: 'হ্যাঁ। সমস্ত হিসাব, ইনভয়েস, কোটেশন ও মুনাফা সরাসরি বাংলাদেশি টাকা (৳ BDT) এবং দেশীয় কমা বিন্যাসে (যেমন ৳ ১,২৫,০০০) পরিচালিত হয়।',
  },
  {
    qEn: 'Can I manage inventory for flex rolls, vinyl, and solvent inks?',
    qBn: 'ফ্লেক্স রোল, ভিনাইল এবং কালির ইনভেন্টরি কি ট্র্যাক করা যায়?',
    aEn: 'Yes. PrintERP includes a dedicated roll media manager. It tracks master rolls by width (e.g. 10ft × 164ft = 1,640 SFT), subtracts square footage as jobs finish, accounts for 5% operator loading scrap, and alerts you when rolls fall below safety thresholds.',
    aBn: 'হ্যাঁ। প্রিন্টইআরপিতে রয়েছে রোল ট্র্যাকার। প্রতিটি রোলের প্রস্থ ও দৈর্ঘ্য (যেমন ১০ ফিট × ১৬৪ ফিট = ১,৬৪০ এসএফটি) অনুযায়ী স্কয়ারফিটের ব্যবহার ও অপচয় লাইভ কমে যায় এবং স্টক ঘাটতি হলে অ্যালার্ট দেয়।',
  },
  {
    qEn: 'Can I track production progress on the factory floor?',
    qBn: 'কারখানার ফ্লোরে প্রোডাকশনের অগ্রগতি কি মনিটর করা যায়?',
    aEn: 'Yes. The interactive Production Kanban board lets you visualize every job through queued, RIP/printing, lamination, die-cutting, fabrication, and ready for dispatch. Machine operators also have a dedicated mobile touch station to start and complete jobs.',
    aBn: 'হ্যাঁ। ভিজ্যুয়াল কানবান বোর্ডের মাধ্যমে কোন কাজ প্রিন্ট হচ্ছে, কোনটা লেমিনেশনে আছে আর কোনটা ডেলিভারির জন্য রেডি তা সরাসরি মনিটর করা যায়। অপারেটরদের জন্য রয়েছে বড় বাটনযুক্ত মোবাইল টাচ স্টেশন।',
  },
  {
    qEn: 'Can I manage customer dues and send automatic reminders?',
    qBn: 'গ্রাহকদের বকেয়া খাতা এবং স্বয়ংক্রিয় তাগাদা পাঠানো কি সম্ভব?',
    aEn: 'Yes. Track partial advance payments, cash receipts, and overdue receivables. With 1-click, you can dispatch polite payment reminder messages with total due balance and payment details directly to your customer’s WhatsApp or via SMS.',
    aBn: 'হ্যাঁ। গ্রাহকের আংশিক জমা ও বকেয়া নিখুঁতভাবে রেকর্ড থাকে। মাত্র ১ ক্লিকে গ্রাহকের হোয়াটসঅ্যাপ বা মোবাইলে বকেয়া টাকার ভদ্র রিমাইন্ডার ও পেমেন্ট লিঙ্ক পাঠানো যায়।',
  },
  {
    qEn: 'Can I calculate the real profit on each individual job?',
    qBn: 'প্রতিটি অর্ডারে আসল নিট লাভ কি বের করা সম্ভব?',
    aEn: 'Absolutely. PrintERP’s job costing engine deducts the bill of materials (media, ink, grommets, ACP, frame pipe), electricity/machine run time, operator labor, transport, and installation fees from the invoice total to calculate your real net profit margin.',
    aBn: 'নিশ্চিতভাবেই। প্রিন্টইআরপির জব কস্টিং ইঞ্জিন মেটেরিয়াল, কালি, বিদ্যুৎ, কারিগরের মজুরি এবং পরিবহন খরচ বিল থেকে স্বয়ংক্রিয়ভাবে বাদ দিয়ে আপনাকে প্রতি অর্ডারে আসল নেট প্রফিট দেখিয়ে দেয়।',
  },
  {
    qEn: 'Can multiple employees use PrintERP at the same time?',
    qBn: 'একসাথে কি একাধিক কর্মচারী সফটওয়্যারটি ব্যবহার করতে পারবে?',
    aEn: 'Yes. PrintERP features a 7-persona Role-Based Access Control (RBAC) system. Business owners, sales managers, graphic designers, production managers, operators, and delivery staff each log into tailored interfaces showing only the information relevant to their job.',
    aBn: 'হ্যাঁ। ভূমিকা ভিত্তিক পারমিশন (RBAC) সিস্টেমের কারণে মালিক, সেলসম্যান, ডিজাইনার, প্রোডাকশন ম্যানেজার ও অপারেটররা যার যার নির্দিষ্ট প্যানেলে সুরক্ষিতভাবে কাজ করতে পারবেন।',
  },
  {
    qEn: 'Can I manage multiple branches or factory locations?',
    qBn: 'একাধিক শাখা বা কারখানা কি একটি একাউন্টে পরিচালনা করা যায়?',
    aEn: 'Yes! Business and Enterprise plans allow multi-branch operations. You can run your Arambagh sales counter, Fakirapool offset press, and Gazipur fabrication factory under one unified organization with separated or consolidated reporting.',
    aBn: 'হ্যাঁ! বিজনেস ও এন্টারপ্রাইজ প্ল্যানে একাধিক শাখা সাপোর্ট করে। সেলস শোরুম ও মূল কারখানা আলাদা লোকেশনে থাকলেও এক জায়গা থেকেই পুরো ব্যবসার হিসাব রাখা সম্ভব।',
  },
  {
    qEn: 'Is PrintERP mobile friendly and works on smartphones?',
    qBn: 'প্রিন্টইআরপি কি স্মার্টফোনে ব্যবহার উপযোগী?',
    aEn: 'PrintERP is built 100% mobile-first as an installable Progressive Web App (PWA). Shop owners can check today’s sales, approve quotes, and track production from anywhere using their Android or iPhone.',
    aBn: 'প্রিন্টইআরপি সম্পূর্ণ মোবাইল-ফার্স্ট পিডব্লিউএ (PWA) প্রযুক্তিতে তৈরি। ফলে কম্পিউটার ছাড়াও যেকোনো সাধারণ স্মার্টফোনে লাইভ সেলস, অর্ডার ও প্রোডাকশন পরিচালনা করা যায়।',
  },
]
