import type { PermissionAction, PermissionModule } from '@/types/rbac.types'
import type { FeatureCode } from '@/types/subscription.types'

export interface NavItem {
  key: string
  title: string
  titleBn: string
  href: string
  icon: string
  exact?: boolean
  badge?: string
  badgeVariant?: 'live' | 'fast' | 'pwa' | 'pro' | 'default'
  permission?: {
    action: PermissionAction
    resource: PermissionModule | string
  }
  featureGate?: FeatureCode
  isPrimaryAction?: boolean
  ownerOnly?: boolean
  hasDividerBelow?: boolean
  children?: NavItem[]
}

export interface NavSection {
  id: 'today' | 'work' | 'resources' | 'specialized' | 'management' | 'settings'
  title: string
  titleBn: string
  items: NavItem[]
}

export function getNavigationConfig(_tenantSlug?: string): NavSection[] {
  return [
    {
      id: 'today',
      title: '',
      titleBn: '',
      items: [
        {
          key: 'new-work',
          title: 'New Work',
          titleBn: 'নতুন কাজ',
          href: '/sales/new-work',
          icon: 'Plus',
          isPrimaryAction: true,
          badge: 'POS',
          badgeVariant: 'fast',
          permission: { action: 'create', resource: 'orders' },
        },
        {
          key: 'dashboard',
          title: 'Dashboard',
          titleBn: 'ড্যাশবোর্ড',
          href: '/dashboard',
          icon: 'LayoutDashboard',
          exact: true,
          hasDividerBelow: true,
        },
        {
          key: 'quotations',
          title: 'Quotations',
          titleBn: 'কোটেশন',
          href: '/quotations',
          icon: 'FileSpreadsheet',
          permission: { action: 'view', resource: 'quotations' },
        },
        {
          key: 'billing',
          title: 'Bills',
          titleBn: 'বিল ও জমা',
          href: '/billing',
          icon: 'Receipt',
          permission: { action: 'view', resource: 'invoices' },
        },
        {
          key: 'customers',
          title: 'Customers',
          titleBn: 'কাস্টমার',
          href: '/customers',
          icon: 'Users',
          permission: { action: 'view', resource: 'customers' },
        },
        {
          key: 'orders',
          title: 'Orders & Jobs',
          titleBn: 'কাজের অর্ডার ও জব',
          href: '/orders',
          icon: 'ShoppingBag',
          permission: { action: 'view', resource: 'orders' },
          hasDividerBelow: true,
        },
      ],
    },
    {
      id: 'work',
      title: 'Work',
      titleBn: 'কাজ',
      items: [
        {
          key: 'design',
          title: 'Design',
          titleBn: 'ডিজাইন',
          href: '/design',
          icon: 'Palette',
          permission: { action: 'view', resource: 'design' },
        },
        {
          key: 'production',
          title: 'Printing',
          titleBn: 'ছাপাখানা',
          href: '/production',
          icon: 'Printer',
          exact: true,
          permission: { action: 'view', resource: 'production' },
        },
        {
          key: 'finishing',
          title: 'Finishing & Fabrication',
          titleBn: 'ফিনিশিং ও তৈরি',
          href: '/finishing',
          icon: 'Scissors',
          permission: { action: 'view', resource: 'production' },
        },
        {
          key: 'delivery',
          title: 'Delivery',
          titleBn: 'ডেলিভারি',
          href: '/delivery',
          icon: 'Truck',
          permission: { action: 'view', resource: 'delivery' },
          hasDividerBelow: true,
        },
      ],
    },
    {
      id: 'resources',
      title: 'Shop',
      titleBn: 'দোকান',
      items: [
        {
          key: 'floor_consumption',
          title: 'Used Materials',
          titleBn: 'ব্যবহৃত কাঁচামাল',
          href: '/production/floor-consumption',
          icon: 'Flame',
          permission: { action: 'view', resource: 'production' },
        },
        {
          key: 'machineries',
          title: 'Machines',
          titleBn: 'মেশিন',
          href: '/production/machineries',
          icon: 'Cpu',
          permission: { action: 'view', resource: 'machineries' },
          hasDividerBelow: true,
        },
      ],
    },
    {
      id: 'specialized',
      title: 'Terminal',
      titleBn: 'টার্মিনাল',
      items: [
        {
          key: 'operator',
          title: 'Operator',
          titleBn: 'অপারেটর',
          href: '/operator',
          icon: 'Cpu',
          permission: { action: 'view', resource: 'production' },
          hasDividerBelow: true,
        },
      ],
    },
    {
      id: 'management',
      title: '',
      titleBn: '',
      items: [
        {
          key: 'inventory',
          title: 'Stock',
          titleBn: 'কাঁচামাল ও স্টক',
          href: '/inventory',
          icon: 'Package',
          permission: { action: 'view', resource: 'inventory' },
        },
        {
          key: 'products',
          title: 'Items',
          titleBn: 'পণ্য তালিকা',
          href: '/products',
          icon: 'Layers',
          permission: { action: 'view', resource: 'products' },
        },
        {
          key: 'pricing',
          title: 'Pricing',
          titleBn: 'দর তালিকা',
          href: '/pricing',
          icon: 'Calculator',
          permission: { action: 'view', resource: 'pricing' },
        },
        {
          key: 'suppliers',
          title: 'Suppliers',
          titleBn: 'সাপ্লায়ার',
          href: '/suppliers',
          icon: 'Building2',
          permission: { action: 'view', resource: 'inventory' },
          hasDividerBelow: true,
        },
        {
          key: 'accounting',
          title: 'Money',
          titleBn: 'টাকা-পয়সা',
          href: '/accounting',
          icon: 'Landmark',
          exact: true,
          permission: { action: 'view', resource: 'payments' },
          children: [
            {
              key: 'acc_dashboard',
              title: 'Dashboard',
              titleBn: 'ফাইন্যান্স ড্যাশবোর্ড',
              href: '/accounting',
              icon: 'LayoutDashboard',
              exact: true,
              permission: { action: 'view', resource: 'payments' },
            },
            {
              key: 'acc_cash_bank',
              title: 'Cash & Bank',
              titleBn: 'ক্যাশ ও ব্যাংক',
              href: '/accounting?tab=cash-bank',
              icon: 'Wallet',
              permission: { action: 'view', resource: 'payments' },
            },
            {
              key: 'acc_receivables',
              title: 'Customer Due',
              titleBn: 'কাস্টমার বাকি',
              href: '/accounting?tab=receivables',
              icon: 'Users',
              permission: { action: 'view', resource: 'payments' },
            },
            {
              key: 'acc_payables',
              title: 'Supplier Due',
              titleBn: 'মহাজন বাকি',
              href: '/accounting?tab=payables',
              icon: 'ShoppingBag',
              permission: { action: 'view', resource: 'payments' },
            },
            {
              key: 'acc_expenses',
              title: 'Expenses',
              titleBn: 'খরচ',
              href: '/accounting?tab=expenses',
              icon: 'TrendingDown',
              permission: { action: 'view', resource: 'payments' },
            },
            {
              key: 'acc_transactions',
              title: 'Transactions',
              titleBn: 'লেনদেন',
              href: '/accounting?tab=transactions',
              icon: 'Receipt',
              permission: { action: 'view', resource: 'payments' },
            },
            {
              key: 'acc_closings',
              title: 'Close Day',
              titleBn: 'দিন শেষ',
              href: '/accounting?tab=cash-closing',
              icon: 'Clock',
              permission: { action: 'view', resource: 'payments' },
            },
            {
              key: 'acc_reports',
              title: 'Money Reports',
              titleBn: 'টাকার হিসাব',
              href: '/accounting?tab=reports',
              icon: 'BarChart3',
              permission: { action: 'view', resource: 'payments' },
            },
          ],
        },
        {
          key: 'costing',
          title: 'Cost & Profit',
          titleBn: 'খরচ ও লাভ',
          href: '/costing',
          icon: 'Calculator',
          permission: { action: 'view', resource: 'reports' },
        },
        {
          key: 'tax',
          title: 'Tax & VAT',
          titleBn: 'ট্যাক্স ও ভ্যাট',
          href: '/tax',
          icon: 'FileCheck2',
          permission: { action: 'manage', resource: 'settings' },
        },
        {
          key: 'reports',
          title: 'Reports',
          titleBn: 'রিপোর্ট ও হিসাব',
          href: '/reports',
          icon: 'BarChart3',
          permission: { action: 'view', resource: 'reports' },
          hasDividerBelow: true,
        },
        {
          key: 'hr',
          title: 'Staff',
          titleBn: 'স্টাফ ও বেতন',
          href: '/hr',
          icon: 'Users2',
          exact: true,
          permission: { action: 'view', resource: 'hr' },
          hasDividerBelow: true,
          children: [
            {
              key: 'hr_overview',
              title: 'Overview',
              titleBn: 'ওভারভিউ',
              href: '/hr',
              icon: 'LayoutDashboard',
              exact: true,
              permission: { action: 'view', resource: 'hr' },
            },
            {
              key: 'hr_employees',
              title: 'Employees',
              titleBn: 'কর্মী',
              href: '/hr/employees',
              icon: 'Users',
              permission: { action: 'view', resource: 'hr' },
            },
            {
              key: 'hr_attendance',
              title: 'Attendance',
              titleBn: 'হাজিরা',
              href: '/hr/attendance',
              icon: 'UserCheck',
              permission: { action: 'view', resource: 'hr' },
            },
            {
              key: 'hr_payroll',
              title: 'Payroll',
              titleBn: 'বেতন ও মজুরি',
              href: '/hr/payroll',
              icon: 'Wallet',
              permission: { action: 'view', resource: 'hr' },
            },
            {
              key: 'hr_advances',
              title: 'Advances',
              titleBn: 'অগ্রিম',
              href: '/hr/advances',
              icon: 'Coins',
              permission: { action: 'view', resource: 'hr' },
            },
            {
              key: 'hr_reports',
              title: 'Reports',
              titleBn: 'রিপোর্ট',
              href: '/hr/reports',
              icon: 'FileSpreadsheet',
              permission: { action: 'view', resource: 'hr' },
            },
          ],
        },
      ],
    },
    {
      id: 'settings',
      title: '',
      titleBn: '',
      items: [
        {
          key: 'company_settings',
          title: 'Settings',
          titleBn: 'সেটিংস',
          href: '/settings',
          icon: 'Settings',
          exact: true,
          permission: { action: 'view', resource: 'settings' },
          hasDividerBelow: true,
          children: [
            {
              key: 'settings_overview',
              title: 'Overview',
              titleBn: 'মূল সেটিংস',
              href: '/settings',
              icon: 'LayoutDashboard',
              exact: true,
              permission: { action: 'view', resource: 'settings' },
            },
            {
              key: 'settings_company',
              title: 'Shop Profile',
              titleBn: 'দোকানের তথ্য',
              href: '/settings/company',
              icon: 'Building2',
              permission: { action: 'view', resource: 'settings' },
            },
            {
              key: 'settings_branding',
              title: 'Logo & Colors',
              titleBn: 'লোগো ও রঙ',
              href: '/settings/branding',
              icon: 'Palette',
              permission: { action: 'view', resource: 'settings' },
            },
            {
              key: 'settings_localization',
              title: 'Language & Formats',
              titleBn: 'ভাষা ও মুদ্রা',
              href: '/settings/localization',
              icon: 'Globe2',
              permission: { action: 'view', resource: 'settings' },
            },
            {
              key: 'settings_numbering',
              title: 'Bill Numbers',
              titleBn: 'বিল নাম্বারিং',
              href: '/settings/document-numbering',
              icon: 'Hash',
              permission: { action: 'manage', resource: 'settings' },
            },
            {
              key: 'settings_templates',
              title: 'Print Formats',
              titleBn: 'প্রিন্ট ফরম্যাট',
              href: '/settings/documents',
              icon: 'FileText',
              permission: { action: 'view', resource: 'settings' },
            },
            {
              key: 'settings_automations',
              title: 'Auto Rules',
              titleBn: 'অটো নিয়ম',
              href: '/settings/automations',
              icon: 'Workflow',
              permission: { action: 'manage', resource: 'settings' },
            },
            {
              key: 'settings_branches',
              title: 'Branches',
              titleBn: 'শাখা',
              href: '/settings/branches',
              icon: 'Building',
              permission: { action: 'manage', resource: 'branches' },
              ownerOnly: true,
            },
            {
              key: 'settings_attendance',
              title: 'Attendance',
              titleBn: 'হাজিরা',
              href: '/settings/attendance',
              icon: 'QrCode',
              permission: { action: 'view', resource: 'settings' },
            },
            {
              key: 'settings_notifications',
              title: 'SMS Alerts',
              titleBn: 'এসএমএস ও এলার্ট',
              href: '/settings/notifications',
              icon: 'Bell',
              permission: { action: 'manage', resource: 'settings' },
            },
            {
              key: 'settings_email',
              title: 'Email Settings',
              titleBn: 'ইমেইল',
              href: '/settings/email',
              icon: 'Mail',
              permission: { action: 'manage', resource: 'settings' },
            },
            {
              key: 'settings_users',
              title: 'Team Users',
              titleBn: 'টিম ব্যবহারকারী',
              href: '/settings/users',
              icon: 'Users',
              permission: { action: 'manage', resource: 'users' },
            },
            {
              key: 'settings_roles',
              title: 'Roles & Permissions',
              titleBn: 'অনুমতি ও রোলস',
              href: '/settings/roles',
              icon: 'ShieldCheck',
              permission: { action: 'manage', resource: 'users' },
            },
            {
              key: 'settings_subscription',
              title: 'My Plan',
              titleBn: 'প্ল্যান ও প্যাকেজ',
              href: '/settings/subscription',
              icon: 'Crown',
              permission: { action: 'manage', resource: 'settings' },
            },
          ],
        },
        {
          key: 'trash',
          title: 'Recycle Bin',
          titleBn: 'রিসাইকেল বিন',
          href: '/trash',
          icon: 'Trash2',
          permission: { action: 'view', resource: 'settings' },
        },
      ],
    },
  ]
}
