import { MeasurementUnit } from '@/types/business.types'

export const UNITS_OF_MEASUREMENT: MeasurementUnit[] = [
  {
    code: 'sft',
    name_en: 'Square Feet',
    name_bn: 'বর্গফুট',
    symbol_en: 'sq.ft',
    symbol_bn: 'বর্গফুট',
    category: 'area',
  },
  {
    code: 'rft',
    name_en: 'Running Feet',
    name_bn: 'রানিং ফুট',
    symbol_en: 'r.ft',
    symbol_bn: 'রানিং ফুট',
    category: 'length',
  },
  {
    code: 'sqinch',
    name_en: 'Square Inch',
    name_bn: 'বর্গ ইঞ্চি',
    symbol_en: 'sq.in',
    symbol_bn: 'বর্গ ইঞ্চি',
    category: 'area',
  },
  {
    code: 'sqm',
    name_en: 'Square Meter',
    name_bn: 'বর্গ মিটার',
    symbol_en: 'sq.m',
    symbol_bn: 'বর্গ মিটার',
    category: 'area',
  },
  {
    code: 'pcs',
    name_en: 'Pieces',
    name_bn: 'পিস / টি',
    symbol_en: 'pcs',
    symbol_bn: 'টি',
    category: 'quantity',
  },
  {
    code: 'pack',
    name_en: 'Packet / Pack',
    name_bn: 'প্যাকেট',
    symbol_en: 'pkt',
    symbol_bn: 'প্যাকেট',
    category: 'quantity',
  },
  {
    code: 'ream',
    name_en: 'Ream (500 sheets)',
    name_bn: 'রিম (৫০০ তা)',
    symbol_en: 'ream',
    symbol_bn: 'রিম',
    category: 'quantity',
  },
  {
    code: 'gross',
    name_en: 'Gross (144 pcs)',
    name_bn: 'গ্রস (১৪৪ টি)',
    symbol_en: 'grs',
    symbol_bn: 'গ্রস',
    category: 'quantity',
  },
  {
    code: 'thaan',
    name_en: 'Thaan (Fabric Roll)',
    name_bn: 'থান (কাপড়ের রোল)',
    symbol_en: 'thn',
    symbol_bn: 'থান',
    category: 'length',
  },
  {
    code: 'meter',
    name_en: 'Meter',
    name_bn: 'মিটার',
    symbol_en: 'm',
    symbol_bn: 'মি.',
    category: 'length',
  },
  {
    code: 'inch',
    name_en: 'Inch',
    name_bn: 'ইঞ্চি',
    symbol_en: 'in',
    symbol_bn: 'ইঞ্চি',
    category: 'length',
  },
  {
    code: 'kg',
    name_en: 'Kilogram',
    name_bn: 'কিলোগ্রাম',
    symbol_en: 'kg',
    symbol_bn: 'কেজি',
    category: 'weight',
  },
]
