'use client'

import React, { useState, useEffect, Suspense } from 'react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import {
  Shield,
  Lock,
  Mail,
  ShieldAlert,
  Sparkles,
  Server,
  Eye,
  EyeOff,
  RefreshCw,
  KeyRound,
  ArrowRight,
  ChevronLeft,
  CheckCircle2,
} from 'lucide-react'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'
import { platformLoginAction } from '@/actions/platform-auth.actions'

function PlatformLoginForm() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [mfaCode, setMfaCode] = useState('')
  const [requiresMfa, setRequiresMfa] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [isNetworkError, setIsNetworkError] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const router = useRouter()
  const searchParams = useSearchParams()

  useEffect(() => {
    const errParam = searchParams.get('error')
    if (errParam === 'unauthorized') {
      setError('Unauthorized: This account does not possess Platform Administration privileges.')
    } else if (errParam === 'disabled') {
      setError('Access Denied: This platform administrator account has been deactivated.')
    }
  }, [searchParams])

  const executeSignIn = async (e?: React.FormEvent) => {
    if (e) e.preventDefault()
    if (isLoading) return

    setIsLoading(true)
    setError(null)
    setIsNetworkError(false)

    const redirectTo = searchParams.get('redirectTo') || '/platform'
    const formData = new FormData()
    formData.append('email', email)
    formData.append('password', password)
    formData.append('redirectTo', redirectTo)
    if (mfaCode) {
      formData.append('mfaCode', mfaCode)
    }

    try {
      const res = await platformLoginAction(formData)

      if (res.success && res.redirectUrl) {
        window.location.href = res.redirectUrl
      } else if (res.requiresMfa || res.mfaRequired) {
        setRequiresMfa(true)
        setError(res.error || null)
      } else {
        setError(res.error || 'Unable to sign in. Check your platform credentials and try again.')
      }
    } catch (err: any) {
      if (!navigator.onLine || err?.message?.includes('network') || err?.message?.includes('fetch')) {
        setIsNetworkError(true)
        setError('Unable to connect. Please verify network connectivity and retry.')
      } else {
        setError(err?.message || 'A security error occurred during platform authentication.')
      }
    } finally {
      setIsLoading(false)
    }
  }

  const fillDemoCredentials = () => {
    setEmail('admin@printerp.com.bd')
    setPassword('Admin@123456')
    setError(null)
  }

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col justify-center items-center p-4 sm:p-6 font-sans selection:bg-indigo-500 selection:text-white">
      {/* Background Glow */}
      <div className="fixed inset-0 pointer-events-none bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.15),rgba(255,255,255,0))]" />

      <div className="w-full max-w-md relative z-10 space-y-6">
        {/* Brand Header */}
        <div className="text-center space-y-2">
          <div className="inline-flex items-center justify-center h-12 w-12 rounded-2xl bg-gradient-to-br from-indigo-500 via-purple-600 to-pink-600 text-white shadow-xl shadow-indigo-500/25 ring-1 ring-white/20 mb-2">
            <Server className="h-6 w-6" />
          </div>
          <div className="flex items-center justify-center gap-2">
            <span className="font-mono text-xs uppercase tracking-widest text-indigo-400 font-bold">
              PrintERP Platform
            </span>
            <span className="text-[10px] px-2 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 font-mono font-bold border border-indigo-500/30">
              RESTRICTED
            </span>
          </div>
          <div className="text-xs text-slate-400 font-medium">Platform Administration Console</div>
          <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-white pt-1">
            {requiresMfa ? 'Two-Factor Verification' : 'Console Sign In'}
          </h1>
          <p className="text-xs text-slate-400">
            {requiresMfa
              ? 'Enter the 6-digit TOTP code generated by your authenticator device.'
              : 'Privileged access exclusively for verified PrintERP platform administrators.'}
          </p>
        </div>

        {/* Login Card */}
        <Card className="bg-slate-900/90 border-slate-800 shadow-2xl backdrop-blur-xl text-slate-100">
          <CardHeader className="pb-4">
            <div className="flex items-center justify-between flex-wrap gap-2">
              <CardTitle className="text-base font-bold text-slate-200 flex items-center gap-2">
                <Shield className="h-4 w-4 text-indigo-400" />
                <span>{requiresMfa ? 'MFA Security Challenge' : 'Authentication'}</span>
              </CardTitle>
            </div>
            <CardDescription className="text-slate-400 text-xs">
              {requiresMfa
                ? 'Your account has Multi-Factor Authentication enabled.'
                : 'Authenticate with verified platform-level credentials.'}
            </CardDescription>
          </CardHeader>

          <form onSubmit={executeSignIn} noValidate>
            <CardContent className="space-y-4">
              {error && (
                <div className="rounded-xl bg-red-950/60 p-3 text-xs text-red-200 border border-red-800/80 flex items-start gap-2.5">
                  <ShieldAlert className="h-4 w-4 text-red-400 shrink-0 mt-0.5" />
                  <div className="flex-1">
                    <span>{error}</span>
                    {isNetworkError && (
                      <div className="mt-2">
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => executeSignIn()}
                          className="text-xs h-7 border-red-700 bg-red-900/40 text-white hover:bg-red-900"
                        >
                          <RefreshCw className="h-3 w-3 mr-1" />
                          Try Again
                        </Button>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {requiresMfa ? (
                /* MFA Verification Step */
                <div className="space-y-4 animate-in fade-in-50 duration-200">
                  <div className="p-3 rounded-xl bg-indigo-950/40 border border-indigo-800/50 text-xs text-indigo-200 flex items-center gap-2.5">
                    <KeyRound className="h-4 w-4 text-indigo-400 shrink-0" />
                    <span>Signing in as: <strong className="text-white">{email}</strong></span>
                  </div>

                  <div className="space-y-1.5">
                    <Label htmlFor="platform-mfa" className="text-xs text-slate-300">
                      6-Digit Authenticator Token
                    </Label>
                    <Input
                      id="platform-mfa"
                      type="text"
                      inputMode="numeric"
                      pattern="[0-9]*"
                      maxLength={6}
                      autoFocus
                      required
                      autoComplete="one-time-code"
                      value={mfaCode}
                      onChange={(e) => setMfaCode(e.target.value.replace(/\D/g, ''))}
                      icon={<KeyRound className="h-4 w-4 text-slate-400" />}
                      placeholder="123456"
                      className="bg-slate-950/60 border-slate-800 text-white placeholder:text-slate-600 focus-visible:ring-indigo-500 font-mono tracking-widest text-center text-lg h-12"
                    />
                  </div>

                  <div className="flex items-center justify-between gap-2 pt-2">
                    <button
                      type="button"
                      onClick={() => {
                        setRequiresMfa(false)
                        setError(null)
                      }}
                      className="text-xs text-slate-400 hover:text-white flex items-center gap-1 min-h-[36px]"
                    >
                      <ChevronLeft className="h-3.5 w-3.5" />
                      <span>Back to credentials</span>
                    </button>

                    <Button
                      type="submit"
                      disabled={isLoading || mfaCode.length !== 6}
                      className="bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white font-bold text-xs py-2 h-10 px-5 shadow-lg shadow-indigo-600/30 min-h-[40px]"
                    >
                      {isLoading ? 'Verifying...' : 'Verify & Sign In'}
                    </Button>
                  </div>
                </div>
              ) : (
                /* Standard Credentials Step */
                <>
                  <div className="space-y-1.5">
                    <Label htmlFor="platform-email" className="text-xs text-slate-300">
                      Platform Email
                    </Label>
                    <Input
                      id="platform-email"
                      type="email"
                      required
                      autoComplete="email"
                      autoCapitalize="none"
                      autoCorrect="off"
                      spellCheck={false}
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      icon={<Mail className="h-4 w-4 text-slate-400" />}
                      placeholder="admin@printerp.com.bd"
                      className="bg-slate-950/60 border-slate-800 text-white placeholder:text-slate-600 focus-visible:ring-indigo-500"
                    />
                  </div>

                  <div className="space-y-1.5">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="platform-password" className="text-xs text-slate-300">
                        Password
                      </Label>
                      <Link
                        href="/platform/forgot-password"
                        className="text-xs text-indigo-400 hover:text-indigo-300 font-medium py-1 min-h-[36px] flex items-center"
                      >
                        Forgot Password?
                      </Link>
                    </div>
                    <Input
                      id="platform-password"
                      type={showPassword ? 'text' : 'password'}
                      required
                      autoComplete="current-password"
                      autoCapitalize="none"
                      autoCorrect="off"
                      spellCheck={false}
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      icon={<Lock className="h-4 w-4 text-slate-400" />}
                      placeholder="••••••••••••"
                      className="bg-slate-950/60 border-slate-800 text-white placeholder:text-slate-600 focus-visible:ring-indigo-500"
                      rightElement={
                        <button
                          type="button"
                          onClick={() => setShowPassword(!showPassword)}
                          className="p-2 text-slate-400 hover:text-slate-200 transition-colors focus:outline-none min-h-[44px] min-w-[44px] flex items-center justify-center cursor-pointer"
                          aria-label={showPassword ? 'Hide password' : 'Show password'}
                        >
                          {showPassword ? (
                            <EyeOff className="h-4 w-4" />
                          ) : (
                            <Eye className="h-4 w-4" />
                          )}
                        </button>
                      }
                    />
                  </div>

                  {/* Quick Dev/Demo Credentials Helper */}
                  <div className="flex items-center justify-between text-[11px] px-1 text-slate-400">
                    <span className="text-slate-500">Root Admin Demo:</span>
                    <button
                      type="button"
                      onClick={fillDemoCredentials}
                      className="text-indigo-400 hover:text-indigo-300 font-mono font-semibold underline underline-offset-2 cursor-pointer transition-colors"
                    >
                      Fill Default Credentials
                    </button>
                  </div>

                  {/* Security Notice */}
                  <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 text-[11px] text-slate-400 space-y-1">
                    <div className="font-semibold text-slate-300 flex items-center gap-1.5">
                      <Shield className="h-3 w-3 text-indigo-400" />
                      Privileged Platform Authorization
                    </div>
                    <div>
                      Platform Administrator sessions have full root oversight over PrintERP infrastructure. All authentication attempts and privileged actions are cryptographically audited.
                    </div>
                  </div>

                  <Button
                    type="submit"
                    disabled={isLoading}
                    className="w-full bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white font-bold text-xs py-2.5 h-11 shadow-lg shadow-indigo-600/30 min-h-[44px]"
                  >
                    {isLoading ? 'Authenticating...' : 'Sign In to Console'}
                  </Button>
                </>
              )}
            </CardContent>

            <CardFooter className="pt-2 pb-5 text-center text-xs text-slate-500 border-t border-slate-800/60 justify-center">
              <div>
                Looking for your business ERP?{' '}
                <Link href="/login" className="text-indigo-400 hover:underline font-semibold">
                  Go to Tenant Login
                </Link>
              </div>
            </CardFooter>
          </form>
        </Card>
      </div>
    </div>
  )
}

export default function PlatformLoginPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-slate-950 flex items-center justify-center text-slate-400">
          Loading platform console...
        </div>
      }
    >
      <PlatformLoginForm />
    </Suspense>
  )
}

