-- Migration 118: Performance Covering Indexes for Foreign Keys & Tenant Tables
-- Prioritizes hot tables (invoices, payments, orders, production, inventory, customers, products)
-- Adds covering foreign key indexes and (company_id, created_at DESC) / (company_id, status) compound indexes.

-- ==============================================================================
-- 1. HOT TABLES (High Volume / Critical Business Queries)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_attendance_records_branch_id ON public.attendance_records (branch_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_job_order_id ON public.attendance_records (job_order_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_location_id ON public.attendance_records (location_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_qr_token_id ON public.attendance_records (qr_token_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_shift_id ON public.attendance_records (shift_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_comp_created_desc ON public.attendance_records (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_customers_district_id ON public.customers (district_id);
CREATE INDEX IF NOT EXISTS idx_customers_division_id ON public.customers (division_id);
CREATE INDEX IF NOT EXISTS idx_customers_upazila_id ON public.customers (upazila_id);
CREATE INDEX IF NOT EXISTS idx_customers_comp_created_desc ON public.customers (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_rolls_branch_id ON public.inventory_rolls (branch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_rolls_grn_id ON public.inventory_rolls (grn_id);
CREATE INDEX IF NOT EXISTS idx_inventory_rolls_location_id ON public.inventory_rolls (location_id);
CREATE INDEX IF NOT EXISTS idx_inventory_rolls_purchase_order_id ON public.inventory_rolls (purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_inventory_rolls_comp_created_desc ON public.inventory_rolls (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_branch_id ON public.invoices (branch_id);
CREATE INDEX IF NOT EXISTS idx_invoices_customer_id ON public.invoices (customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_quotation_id ON public.invoices (quotation_id);
CREATE INDEX IF NOT EXISTS idx_invoices_sales_order_id ON public.invoices (sales_order_id);
CREATE INDEX IF NOT EXISTS idx_invoices_salesperson_id ON public.invoices (salesperson_id);
CREATE INDEX IF NOT EXISTS idx_job_orders_invoice_id ON public.job_orders (invoice_id);
CREATE INDEX IF NOT EXISTS idx_job_orders_order_item_id ON public.job_orders (order_item_id);
CREATE INDEX IF NOT EXISTS idx_job_orders_comp_created_desc ON public.job_orders (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_actor_user_id ON public.payments (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_payments_branch_id ON public.payments (branch_id);
CREATE INDEX IF NOT EXISTS idx_payments_customer_id ON public.payments (customer_id);
CREATE INDEX IF NOT EXISTS idx_payments_comp_created_desc ON public.payments (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_production_tasks_assigned_machine_id ON public.production_tasks (assigned_machine_id);
CREATE INDEX IF NOT EXISTS idx_production_tasks_assigned_operator_id ON public.production_tasks (assigned_operator_id);
CREATE INDEX IF NOT EXISTS idx_production_tasks_branch_id ON public.production_tasks (branch_id);
CREATE INDEX IF NOT EXISTS idx_production_tasks_job_order_id ON public.production_tasks (job_order_id);
CREATE INDEX IF NOT EXISTS idx_production_tasks_production_job_id ON public.production_tasks (production_job_id);
CREATE INDEX IF NOT EXISTS idx_production_tasks_rework_parent_task_id ON public.production_tasks (rework_parent_task_id);
CREATE INDEX IF NOT EXISTS idx_production_tasks_comp_created_desc ON public.production_tasks (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_branch_id ON public.products (branch_id);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_created_by ON public.products (created_by);
CREATE INDEX IF NOT EXISTS idx_products_comp_created_desc ON public.products (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotation_items_product_id ON public.quotation_items (product_id);
CREATE INDEX IF NOT EXISTS idx_quotations_salesperson_id ON public.quotations (salesperson_id);
CREATE INDEX IF NOT EXISTS idx_quotations_comp_created_desc ON public.quotations (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_order_items_product_id ON public.sales_order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_invoice_id ON public.sales_orders (invoice_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_quotation_id ON public.sales_orders (quotation_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_comp_created_desc ON public.sales_orders (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_ledger_branch_id ON public.stock_ledger (branch_id);
CREATE INDEX IF NOT EXISTS idx_stock_ledger_location_id ON public.stock_ledger (location_id);
CREATE INDEX IF NOT EXISTS idx_stock_ledger_production_task_id ON public.stock_ledger (production_task_id);
CREATE INDEX IF NOT EXISTS idx_stock_ledger_comp_created_desc ON public.stock_ledger (company_id, created_at DESC);

-- ==============================================================================
-- 2. FOREIGN KEY COVERING INDEXES (Remaining Domain Tables)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_account_transfers_branch_id ON public.account_transfers (branch_id);
CREATE INDEX IF NOT EXISTS idx_account_transfers_from_account_id ON public.account_transfers (from_account_id);
CREATE INDEX IF NOT EXISTS idx_account_transfers_to_account_id ON public.account_transfers (to_account_id);
CREATE INDEX IF NOT EXISTS idx_account_transfers_transaction_id ON public.account_transfers (transaction_id);
CREATE INDEX IF NOT EXISTS idx_accounts_branch_id ON public.accounts (branch_id);
CREATE INDEX IF NOT EXISTS idx_additional_options_product_id ON public.additional_options (product_id);
CREATE INDEX IF NOT EXISTS idx_attendance_audit_logs_employee_id ON public.attendance_audit_logs (employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_audit_logs_location_id ON public.attendance_audit_logs (location_id);
CREATE INDEX IF NOT EXISTS idx_attendance_corrections_attendance_record_id ON public.attendance_corrections (attendance_record_id);
CREATE INDEX IF NOT EXISTS idx_attendance_corrections_requested_by ON public.attendance_corrections (requested_by);
CREATE INDEX IF NOT EXISTS idx_attendance_corrections_reviewed_by ON public.attendance_corrections (reviewed_by);
CREATE INDEX IF NOT EXISTS idx_attendance_daily_summaries_approved_by_id ON public.attendance_daily_summaries (approved_by_id);
CREATE INDEX IF NOT EXISTS idx_attendance_daily_summaries_branch_id ON public.attendance_daily_summaries (branch_id);
CREATE INDEX IF NOT EXISTS idx_attendance_daily_summaries_job_order_id ON public.attendance_daily_summaries (job_order_id);
CREATE INDEX IF NOT EXISTS idx_attendance_daily_summaries_location_id ON public.attendance_daily_summaries (location_id);
CREATE INDEX IF NOT EXISTS idx_attendance_daily_summaries_shift_id ON public.attendance_daily_summaries (shift_id);
CREATE INDEX IF NOT EXISTS idx_attendance_qr_tokens_generated_by ON public.attendance_qr_tokens (generated_by);
CREATE INDEX IF NOT EXISTS idx_auth_verifications_user_id ON public.auth_verifications (user_id);
CREATE INDEX IF NOT EXISTS idx_bank_statement_lines_matched_journal_line_id ON public.bank_statement_lines (matched_journal_line_id);
CREATE INDEX IF NOT EXISTS idx_bank_statement_lines_matched_transaction_id ON public.bank_statement_lines (matched_transaction_id);
CREATE INDEX IF NOT EXISTS idx_bank_statements_account_id ON public.bank_statements (account_id);
CREATE INDEX IF NOT EXISTS idx_bank_statements_branch_id ON public.bank_statements (branch_id);
CREATE INDEX IF NOT EXISTS idx_bank_statements_imported_by_id ON public.bank_statements (imported_by_id);
CREATE INDEX IF NOT EXISTS idx_cash_closings_account_id ON public.cash_closings (account_id);
CREATE INDEX IF NOT EXISTS idx_cash_closings_adjustment_transaction_id ON public.cash_closings (adjustment_transaction_id);
CREATE INDEX IF NOT EXISTS idx_cash_closings_branch_id ON public.cash_closings (branch_id);
CREATE INDEX IF NOT EXISTS idx_communication_logs_gateway_id ON public.communication_logs (gateway_id);
CREATE INDEX IF NOT EXISTS idx_communication_logs_sent_by ON public.communication_logs (sent_by);
CREATE INDEX IF NOT EXISTS idx_communication_messages_branch_id ON public.communication_messages (branch_id);
CREATE INDEX IF NOT EXISTS idx_communication_messages_sent_by ON public.communication_messages (sent_by);
CREATE INDEX IF NOT EXISTS idx_companies_suspended_by ON public.companies (suspended_by);
CREATE INDEX IF NOT EXISTS idx_company_subscriptions_plan_id ON public.company_subscriptions (plan_id);
CREATE INDEX IF NOT EXISTS idx_customer_communications_logged_by ON public.customer_communications (logged_by);
CREATE INDEX IF NOT EXISTS idx_customer_rates_customer_id ON public.customer_rates (customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_rates_product_id ON public.customer_rates (product_id);
CREATE INDEX IF NOT EXISTS idx_daily_labor_logs_employee_id ON public.daily_labor_logs (employee_id);
CREATE INDEX IF NOT EXISTS idx_delivery_challans_customer_id ON public.delivery_challans (customer_id);
CREATE INDEX IF NOT EXISTS idx_delivery_challans_sales_order_id ON public.delivery_challans (sales_order_id);
CREATE INDEX IF NOT EXISTS idx_design_jobs_customer_id ON public.design_jobs (customer_id);
CREATE INDEX IF NOT EXISTS idx_design_jobs_designer_id ON public.design_jobs (designer_id);
CREATE INDEX IF NOT EXISTS idx_design_jobs_invoice_id ON public.design_jobs (invoice_id);
CREATE INDEX IF NOT EXISTS idx_design_jobs_invoice_request_id ON public.design_jobs (invoice_request_id);
CREATE INDEX IF NOT EXISTS idx_design_jobs_job_order_id ON public.design_jobs (job_order_id);
CREATE INDEX IF NOT EXISTS idx_design_jobs_sales_order_id ON public.design_jobs (sales_order_id);
CREATE INDEX IF NOT EXISTS idx_email_gateways_created_by ON public.email_gateways (created_by);
CREATE INDEX IF NOT EXISTS idx_email_logs_gateway_id ON public.email_logs (gateway_id);
CREATE INDEX IF NOT EXISTS idx_email_logs_sent_by ON public.email_logs (sent_by);
CREATE INDEX IF NOT EXISTS idx_employee_shifts_employee_id ON public.employee_shifts (employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_shifts_shift_id ON public.employee_shifts (shift_id);
CREATE INDEX IF NOT EXISTS idx_employees_branch_id ON public.employees (branch_id);
CREATE INDEX IF NOT EXISTS idx_financial_transactions_branch_id ON public.financial_transactions (branch_id);
CREATE INDEX IF NOT EXISTS idx_financial_transactions_posted_by_id ON public.financial_transactions (posted_by_id);
CREATE INDEX IF NOT EXISTS idx_financial_transactions_reversal_of_id ON public.financial_transactions (reversal_of_id);
CREATE INDEX IF NOT EXISTS idx_financial_write_offs_actor_user_id ON public.financial_write_offs (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_finishing_options_material_id ON public.finishing_options (material_id);
CREATE INDEX IF NOT EXISTS idx_gateway_audit_logs_gateway_id ON public.gateway_audit_logs (gateway_id);
CREATE INDEX IF NOT EXISTS idx_gateway_audit_logs_performed_by ON public.gateway_audit_logs (performed_by);
CREATE INDEX IF NOT EXISTS idx_gateway_integrations_created_by ON public.gateway_integrations (created_by);
CREATE INDEX IF NOT EXISTS idx_gateway_transactions_gateway_id ON public.gateway_transactions (gateway_id);
CREATE INDEX IF NOT EXISTS idx_gateway_webhooks_gateway_id ON public.gateway_webhooks (gateway_id);
CREATE INDEX IF NOT EXISTS idx_goods_received_note_items_po_item_id ON public.goods_received_note_items (po_item_id);
CREATE INDEX IF NOT EXISTS idx_goods_received_notes_branch_id ON public.goods_received_notes (branch_id);
CREATE INDEX IF NOT EXISTS idx_goods_received_notes_company_id ON public.goods_received_notes (company_id);
CREATE INDEX IF NOT EXISTS idx_goods_received_notes_posted_by_id ON public.goods_received_notes (posted_by_id);
CREATE INDEX IF NOT EXISTS idx_goods_received_notes_receiving_location_id ON public.goods_received_notes (receiving_location_id);
CREATE INDEX IF NOT EXISTS idx_goods_received_notes_supplier_id ON public.goods_received_notes (supplier_id);
CREATE INDEX IF NOT EXISTS idx_in_app_notifications_user_id ON public.in_app_notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_installations_customer_id ON public.installations (customer_id);
CREATE INDEX IF NOT EXISTS idx_installations_sales_order_id ON public.installations (sales_order_id);
CREATE INDEX IF NOT EXISTS idx_inventory_adjustments_location_id ON public.inventory_adjustments (location_id);
CREATE INDEX IF NOT EXISTS idx_inventory_adjustments_material_id ON public.inventory_adjustments (material_id);
CREATE INDEX IF NOT EXISTS idx_inventory_locations_branch_id ON public.inventory_locations (branch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_remnants_branch_id ON public.inventory_remnants (branch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_remnants_created_from_task_id ON public.inventory_remnants (created_from_task_id);
CREATE INDEX IF NOT EXISTS idx_inventory_remnants_location_id ON public.inventory_remnants (location_id);
CREATE INDEX IF NOT EXISTS idx_inventory_remnants_material_id ON public.inventory_remnants (material_id);
CREATE INDEX IF NOT EXISTS idx_inventory_remnants_original_roll_id ON public.inventory_remnants (original_roll_id);
CREATE INDEX IF NOT EXISTS idx_inventory_remnants_source_roll_id ON public.inventory_remnants (source_roll_id);
CREATE INDEX IF NOT EXISTS idx_inventory_stock_balances_branch_id ON public.inventory_stock_balances (branch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_stock_balances_location_id ON public.inventory_stock_balances (location_id);
CREATE INDEX IF NOT EXISTS idx_inventory_stock_balances_material_id ON public.inventory_stock_balances (material_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_from_branch_id ON public.inventory_transfers (from_branch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_from_location_id ON public.inventory_transfers (from_location_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_material_id ON public.inventory_transfers (material_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_to_branch_id ON public.inventory_transfers (to_branch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_to_location_id ON public.inventory_transfers (to_location_id);
CREATE INDEX IF NOT EXISTS idx_invoice_requests_customer_id ON public.invoice_requests (customer_id);
CREATE INDEX IF NOT EXISTS idx_invoice_requests_invoice_id ON public.invoice_requests (invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_requests_requested_by_id ON public.invoice_requests (requested_by_id);
CREATE INDEX IF NOT EXISTS idx_job_costings_branch_id ON public.job_costings (branch_id);
CREATE INDEX IF NOT EXISTS idx_job_costings_created_by ON public.job_costings (created_by);
CREATE INDEX IF NOT EXISTS idx_job_costings_customer_id ON public.job_costings (customer_id);
CREATE INDEX IF NOT EXISTS idx_job_costings_job_id ON public.job_costings (job_id);
CREATE INDEX IF NOT EXISTS idx_job_costings_job_order_id ON public.job_costings (job_order_id);
CREATE INDEX IF NOT EXISTS idx_job_costings_product_id ON public.job_costings (product_id);
CREATE INDEX IF NOT EXISTS idx_job_costings_quotation_id ON public.job_costings (quotation_id);
CREATE INDEX IF NOT EXISTS idx_job_costings_sales_order_id ON public.job_costings (sales_order_id);
CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_account_id ON public.journal_entry_lines (account_id);
CREATE INDEX IF NOT EXISTS idx_machineries_branch_id ON public.machineries (branch_id);
CREATE INDEX IF NOT EXISTS idx_machineries_supplier_id ON public.machineries (supplier_id);
CREATE INDEX IF NOT EXISTS idx_machinery_assignments_branch_id ON public.machinery_assignments (branch_id);
CREATE INDEX IF NOT EXISTS idx_machinery_assignments_created_by ON public.machinery_assignments (created_by);
CREATE INDEX IF NOT EXISTS idx_machinery_assignments_operator_id ON public.machinery_assignments (operator_id);
CREATE INDEX IF NOT EXISTS idx_machinery_assignments_production_task_id ON public.machinery_assignments (production_task_id);
CREATE INDEX IF NOT EXISTS idx_machinery_breakdowns_affected_job_order_id ON public.machinery_breakdowns (affected_job_order_id);
CREATE INDEX IF NOT EXISTS idx_machinery_breakdowns_affected_production_job_id ON public.machinery_breakdowns (affected_production_job_id);
CREATE INDEX IF NOT EXISTS idx_machinery_breakdowns_reported_by_id ON public.machinery_breakdowns (reported_by_id);
CREATE INDEX IF NOT EXISTS idx_machinery_maintenances_created_by ON public.machinery_maintenances (created_by);
CREATE INDEX IF NOT EXISTS idx_material_issue_items_issue_id ON public.material_issue_items (issue_id);
CREATE INDEX IF NOT EXISTS idx_material_issue_items_location_id ON public.material_issue_items (location_id);
CREATE INDEX IF NOT EXISTS idx_material_issue_items_material_id ON public.material_issue_items (material_id);
CREATE INDEX IF NOT EXISTS idx_material_issues_branch_id ON public.material_issues (branch_id);
CREATE INDEX IF NOT EXISTS idx_material_issues_issued_by_id ON public.material_issues (issued_by_id);
CREATE INDEX IF NOT EXISTS idx_material_issues_issued_to_id ON public.material_issues (issued_to_id);
CREATE INDEX IF NOT EXISTS idx_material_issues_job_order_id ON public.material_issues (job_order_id);
CREATE INDEX IF NOT EXISTS idx_material_issues_production_task_id ON public.material_issues (production_task_id);
CREATE INDEX IF NOT EXISTS idx_material_issues_request_id ON public.material_issues (request_id);
CREATE INDEX IF NOT EXISTS idx_material_purchase_configs_material_id ON public.material_purchase_configs (material_id);
CREATE INDEX IF NOT EXISTS idx_material_purchase_configs_supplier_id ON public.material_purchase_configs (supplier_id);
CREATE INDEX IF NOT EXISTS idx_material_request_items_location_id ON public.material_request_items (location_id);
CREATE INDEX IF NOT EXISTS idx_material_request_items_material_id ON public.material_request_items (material_id);
CREATE INDEX IF NOT EXISTS idx_material_request_items_request_id ON public.material_request_items (request_id);
CREATE INDEX IF NOT EXISTS idx_material_requests_approved_by_id ON public.material_requests (approved_by_id);
CREATE INDEX IF NOT EXISTS idx_material_requests_branch_id ON public.material_requests (branch_id);
CREATE INDEX IF NOT EXISTS idx_material_requests_job_order_id ON public.material_requests (job_order_id);
CREATE INDEX IF NOT EXISTS idx_material_requests_production_task_id ON public.material_requests (production_task_id);
CREATE INDEX IF NOT EXISTS idx_material_requests_requested_by_id ON public.material_requests (requested_by_id);
CREATE INDEX IF NOT EXISTS idx_material_wastages_job_order_id ON public.material_wastages (job_order_id);
CREATE INDEX IF NOT EXISTS idx_materials_branch_id ON public.materials (branch_id);
CREATE INDEX IF NOT EXISTS idx_materials_created_by ON public.materials (created_by);
CREATE INDEX IF NOT EXISTS idx_otp_requests_tenant_id ON public.otp_requests (tenant_id);
CREATE INDEX IF NOT EXISTS idx_overtime_records_approved_by_id ON public.overtime_records (approved_by_id);
CREATE INDEX IF NOT EXISTS idx_overtime_records_attendance_id ON public.overtime_records (attendance_id);
CREATE INDEX IF NOT EXISTS idx_overtime_records_branch_id ON public.overtime_records (branch_id);
CREATE INDEX IF NOT EXISTS idx_overtime_records_employee_id ON public.overtime_records (employee_id);
CREATE INDEX IF NOT EXISTS idx_overtime_records_payroll_period_id ON public.overtime_records (payroll_period_id);
CREATE INDEX IF NOT EXISTS idx_overtime_records_requested_by_id ON public.overtime_records (requested_by_id);
CREATE INDEX IF NOT EXISTS idx_payment_adjustments_authorized_by_id ON public.payment_adjustments (authorized_by_id);
CREATE INDEX IF NOT EXISTS idx_payroll_items_company_id ON public.payroll_items (company_id);
CREATE INDEX IF NOT EXISTS idx_payroll_periods_approved_by_id ON public.payroll_periods (approved_by_id);
CREATE INDEX IF NOT EXISTS idx_payroll_periods_branch_id ON public.payroll_periods (branch_id);
CREATE INDEX IF NOT EXISTS idx_plan_versions_created_by ON public.plan_versions (created_by);
CREATE INDEX IF NOT EXISTS idx_platform_audit_logs_platform_admin_id ON public.platform_audit_logs (platform_admin_id);
CREATE INDEX IF NOT EXISTS idx_platform_emergency_controls_activated_by ON public.platform_emergency_controls (activated_by);
CREATE INDEX IF NOT EXISTS idx_platform_incidents_created_by ON public.platform_incidents (created_by);
CREATE INDEX IF NOT EXISTS idx_platform_incidents_resolved_by ON public.platform_incidents (resolved_by);
CREATE INDEX IF NOT EXISTS idx_platform_subscriptions_next_plan_id ON public.platform_subscriptions (next_plan_id);
CREATE INDEX IF NOT EXISTS idx_platform_subscriptions_plan_id ON public.platform_subscriptions (plan_id);
CREATE INDEX IF NOT EXISTS idx_platform_subscriptions_previous_plan_id ON public.platform_subscriptions (previous_plan_id);
CREATE INDEX IF NOT EXISTS idx_platform_support_sessions_revoked_by ON public.platform_support_sessions (revoked_by);
CREATE INDEX IF NOT EXISTS idx_platform_system_health_events_company_id ON public.platform_system_health_events (company_id);
CREATE INDEX IF NOT EXISTS idx_platform_system_health_events_resolved_by ON public.platform_system_health_events (resolved_by);
CREATE INDEX IF NOT EXISTS idx_platform_system_settings_updated_by ON public.platform_system_settings (updated_by);
CREATE INDEX IF NOT EXISTS idx_platform_tenant_exports_requested_by ON public.platform_tenant_exports (requested_by);
CREATE INDEX IF NOT EXISTS idx_price_list_items_price_list_id ON public.price_list_items (price_list_id);
CREATE INDEX IF NOT EXISTS idx_price_list_items_product_id ON public.price_list_items (product_id);
CREATE INDEX IF NOT EXISTS idx_price_overrides_authorized_by ON public.price_overrides (authorized_by);
CREATE INDEX IF NOT EXISTS idx_price_overrides_product_id ON public.price_overrides (product_id);
CREATE INDEX IF NOT EXISTS idx_pricing_rules_customer_id ON public.pricing_rules (customer_id);
CREATE INDEX IF NOT EXISTS idx_pricing_rules_product_id ON public.pricing_rules (product_id);
CREATE INDEX IF NOT EXISTS idx_printing_methods_category_id ON public.printing_methods (category_id);
CREATE INDEX IF NOT EXISTS idx_product_formulas_product_id ON public.product_formulas (product_id);
CREATE INDEX IF NOT EXISTS idx_product_price_history_changed_by ON public.product_price_history (changed_by);
CREATE INDEX IF NOT EXISTS idx_product_price_history_company_id ON public.product_price_history (company_id);
CREATE INDEX IF NOT EXISTS idx_product_supplier_prices_product_id ON public.product_supplier_prices (product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON public.product_variants (product_id);
CREATE INDEX IF NOT EXISTS idx_production_jobs_invoice_id ON public.production_jobs (invoice_id);
CREATE INDEX IF NOT EXISTS idx_production_jobs_job_order_id ON public.production_jobs (job_order_id);
CREATE INDEX IF NOT EXISTS idx_production_jobs_sales_order_id ON public.production_jobs (sales_order_id);
CREATE INDEX IF NOT EXISTS idx_production_problem_reports_branch_id ON public.production_problem_reports (branch_id);
CREATE INDEX IF NOT EXISTS idx_production_problem_reports_job_order_id ON public.production_problem_reports (job_order_id);
CREATE INDEX IF NOT EXISTS idx_production_problem_reports_production_job_id ON public.production_problem_reports (production_job_id);
CREATE INDEX IF NOT EXISTS idx_production_problem_reports_reported_by ON public.production_problem_reports (reported_by);
CREATE INDEX IF NOT EXISTS idx_production_problem_reports_resolved_by ON public.production_problem_reports (resolved_by);
CREATE INDEX IF NOT EXISTS idx_production_task_material_requirements_material_id ON public.production_task_material_requirements (material_id);
CREATE INDEX IF NOT EXISTS idx_production_task_material_requirements_production_task_id ON public.production_task_material_requirements (production_task_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_material_id ON public.purchase_order_items (material_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_approved_by_id ON public.purchase_orders (approved_by_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_branch_id ON public.purchase_orders (branch_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_purchase_request_id ON public.purchase_orders (purchase_request_id);
CREATE INDEX IF NOT EXISTS idx_purchase_request_items_material_id ON public.purchase_request_items (material_id);
CREATE INDEX IF NOT EXISTS idx_purchase_request_items_preferred_supplier_id ON public.purchase_request_items (preferred_supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_approved_by_id ON public.purchase_requests (approved_by_id);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_branch_id ON public.purchase_requests (branch_id);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_requested_by_id ON public.purchase_requests (requested_by_id);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_supplier_id ON public.purchase_requests (supplier_id);
CREATE INDEX IF NOT EXISTS idx_saas_subscription_invoices_gateway_transaction_id ON public.saas_subscription_invoices (gateway_transaction_id);
CREATE INDEX IF NOT EXISTS idx_saas_subscription_invoices_plan_id ON public.saas_subscription_invoices (plan_id);
CREATE INDEX IF NOT EXISTS idx_saas_subscription_invoices_subscription_id ON public.saas_subscription_invoices (subscription_id);
CREATE INDEX IF NOT EXISTS idx_salary_advances_approved_by_id ON public.salary_advances (approved_by_id);
CREATE INDEX IF NOT EXISTS idx_salary_advances_branch_id ON public.salary_advances (branch_id);
CREATE INDEX IF NOT EXISTS idx_salary_advances_transaction_id ON public.salary_advances (transaction_id);
CREATE INDEX IF NOT EXISTS idx_salary_payments_branch_id ON public.salary_payments (branch_id);
CREATE INDEX IF NOT EXISTS idx_salary_payments_employee_id ON public.salary_payments (employee_id);
CREATE INDEX IF NOT EXISTS idx_salary_payments_paid_by_id ON public.salary_payments (paid_by_id);
CREATE INDEX IF NOT EXISTS idx_salary_payments_payroll_item_id ON public.salary_payments (payroll_item_id);
CREATE INDEX IF NOT EXISTS idx_salary_payments_payroll_period_id ON public.salary_payments (payroll_period_id);
CREATE INDEX IF NOT EXISTS idx_salary_payments_transaction_id ON public.salary_payments (transaction_id);
CREATE INDEX IF NOT EXISTS idx_shifts_branch_id ON public.shifts (branch_id);
CREATE INDEX IF NOT EXISTS idx_subscription_events_transaction_id ON public.subscription_events (transaction_id);
CREATE INDEX IF NOT EXISTS idx_supplier_items_branch_id ON public.supplier_items (branch_id);
CREATE INDEX IF NOT EXISTS idx_supplier_items_material_id ON public.supplier_items (material_id);
CREATE INDEX IF NOT EXISTS idx_supplier_items_supplier_id ON public.supplier_items (supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_ledger_entries_branch_id ON public.supplier_ledger_entries (branch_id);
CREATE INDEX IF NOT EXISTS idx_supplier_ledger_entries_supplier_id ON public.supplier_ledger_entries (supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_material_prices_company_id ON public.supplier_material_prices (company_id);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_company_id ON public.supplier_payments (company_id);
CREATE INDEX IF NOT EXISTS idx_supplier_price_history_material_id ON public.supplier_price_history (material_id);
CREATE INDEX IF NOT EXISTS idx_supplier_price_history_po_id ON public.supplier_price_history (po_id);
CREATE INDEX IF NOT EXISTS idx_supplier_price_history_supplier_id ON public.supplier_price_history (supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_return_items_grn_item_id ON public.supplier_return_items (grn_item_id);
CREATE INDEX IF NOT EXISTS idx_supplier_return_items_location_id ON public.supplier_return_items (location_id);
CREATE INDEX IF NOT EXISTS idx_supplier_return_items_material_id ON public.supplier_return_items (material_id);
CREATE INDEX IF NOT EXISTS idx_supplier_returns_approved_by_id ON public.supplier_returns (approved_by_id);
CREATE INDEX IF NOT EXISTS idx_supplier_returns_branch_id ON public.supplier_returns (branch_id);
CREATE INDEX IF NOT EXISTS idx_supplier_returns_grn_id ON public.supplier_returns (grn_id);
CREATE INDEX IF NOT EXISTS idx_supplier_returns_purchase_order_id ON public.supplier_returns (purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_supplier_returns_supplier_id ON public.supplier_returns (supplier_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_branch_id ON public.suppliers (branch_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_created_by ON public.suppliers (created_by);
CREATE INDEX IF NOT EXISTS idx_suppliers_updated_by ON public.suppliers (updated_by);
CREATE INDEX IF NOT EXISTS idx_support_conversations_branch_id ON public.support_conversations (branch_id);
CREATE INDEX IF NOT EXISTS idx_support_conversations_created_by ON public.support_conversations (created_by);
CREATE INDEX IF NOT EXISTS idx_support_conversations_resolved_by ON public.support_conversations (resolved_by);
CREATE INDEX IF NOT EXISTS idx_user_branch_access_branch_id ON public.user_branch_access (branch_id);
CREATE INDEX IF NOT EXISTS idx_user_branch_access_user_id ON public.user_branch_access (user_id);
CREATE INDEX IF NOT EXISTS idx_user_permission_overrides_permission_id ON public.user_permission_overrides (permission_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_chats_connection_id ON public.whatsapp_chats (connection_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_connection_id ON public.whatsapp_messages (connection_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_contact_id ON public.whatsapp_messages (contact_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_sent_by_user_id ON public.whatsapp_messages (sent_by_user_id);
CREATE INDEX IF NOT EXISTS idx_workflow_execution_logs_rule_id ON public.workflow_execution_logs (rule_id);
CREATE INDEX IF NOT EXISTS idx_workforce_audit_logs_actor_id ON public.workforce_audit_logs (actor_id);

-- ==============================================================================
-- 3. TENANT COMPOUND FILTER & SORT INDEXES (company_id + created_at / status)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_account_transfers_comp_created_desc ON public.account_transfers (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_account_transfers_comp_status ON public.account_transfers (company_id, status);
CREATE INDEX IF NOT EXISTS idx_accounts_comp_created_desc ON public.accounts (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_additional_options_comp_created_desc ON public.additional_options (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_audit_logs_comp_created_desc ON public.attendance_audit_logs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_corrections_comp_created_desc ON public.attendance_corrections (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_daily_summaries_comp_created_desc ON public.attendance_daily_summaries (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_locations_comp_created_desc ON public.attendance_locations (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_qr_tokens_comp_created_desc ON public.attendance_qr_tokens (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendances_comp_created_desc ON public.attendances (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendances_comp_status ON public.attendances (company_id, status);
CREATE INDEX IF NOT EXISTS idx_bank_accounts_comp_created_desc ON public.bank_accounts (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bank_statement_lines_comp_created_desc ON public.bank_statement_lines (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bank_statements_comp_created_desc ON public.bank_statements (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bank_statements_comp_status ON public.bank_statements (company_id, status);
CREATE INDEX IF NOT EXISTS idx_branches_comp_created_desc ON public.branches (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cash_book_entries_comp_created_desc ON public.cash_book_entries (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cash_closings_comp_created_desc ON public.cash_closings (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cash_closings_comp_status ON public.cash_closings (company_id, status);
CREATE INDEX IF NOT EXISTS idx_communication_logs_comp_created_desc ON public.communication_logs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_communication_logs_comp_status ON public.communication_logs (company_id, status);
CREATE INDEX IF NOT EXISTS idx_communication_messages_comp_status ON public.communication_messages (company_id, status);
CREATE INDEX IF NOT EXISTS idx_communication_templates_comp_created_desc ON public.communication_templates (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_company_settings_comp_created_desc ON public.company_settings (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_company_subscriptions_comp_created_desc ON public.company_subscriptions (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_company_tax_settings_comp_created_desc ON public.company_tax_settings (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_company_users_comp_created_desc ON public.company_users (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_company_users_comp_status ON public.company_users (company_id, status);
CREATE INDEX IF NOT EXISTS idx_customer_communications_comp_created_desc ON public.customer_communications (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customer_rates_comp_created_desc ON public.customer_rates (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_daily_labor_logs_comp_created_desc ON public.daily_labor_logs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_delivery_challans_comp_created_desc ON public.delivery_challans (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_design_jobs_comp_created_desc ON public.design_jobs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_document_templates_config_comp_created_desc ON public.document_templates_config (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employee_shifts_comp_created_desc ON public.employee_shifts (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employees_comp_created_desc ON public.employees (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_expenses_comp_created_desc ON public.expenses (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_financial_periods_comp_created_desc ON public.financial_periods (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_financial_periods_comp_status ON public.financial_periods (company_id, status);
CREATE INDEX IF NOT EXISTS idx_financial_transactions_comp_created_desc ON public.financial_transactions (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_financial_write_offs_comp_created_desc ON public.financial_write_offs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_finishing_options_comp_created_desc ON public.finishing_options (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_goods_received_notes_comp_created_desc ON public.goods_received_notes (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_goods_received_notes_comp_status ON public.goods_received_notes (company_id, status);
CREATE INDEX IF NOT EXISTS idx_in_app_notifications_comp_created_desc ON public.in_app_notifications (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_installation_options_comp_created_desc ON public.installation_options (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_installations_comp_created_desc ON public.installations (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_adjustments_comp_created_desc ON public.inventory_adjustments (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_locations_comp_created_desc ON public.inventory_locations (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_remnants_comp_created_desc ON public.inventory_remnants (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_comp_created_desc ON public.inventory_transfers (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_comp_status ON public.inventory_transfers (company_id, status);
CREATE INDEX IF NOT EXISTS idx_invoice_requests_comp_created_desc ON public.invoice_requests (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_costings_comp_created_desc ON public.job_costings (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_comp_created_desc ON public.journal_entry_lines (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_machineries_comp_created_desc ON public.machineries (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_machinery_assignments_comp_created_desc ON public.machinery_assignments (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_machinery_assignments_comp_status ON public.machinery_assignments (company_id, status);
CREATE INDEX IF NOT EXISTS idx_machinery_breakdowns_comp_created_desc ON public.machinery_breakdowns (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_machinery_maintenances_comp_created_desc ON public.machinery_maintenances (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_machinery_maintenances_comp_status ON public.machinery_maintenances (company_id, status);
CREATE INDEX IF NOT EXISTS idx_material_issues_comp_created_desc ON public.material_issues (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_material_purchase_configs_comp_created_desc ON public.material_purchase_configs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_material_request_items_comp_status ON public.material_request_items (company_id, status);
CREATE INDEX IF NOT EXISTS idx_material_requests_comp_created_desc ON public.material_requests (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_material_wastages_comp_created_desc ON public.material_wastages (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_materials_comp_created_desc ON public.materials (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_message_templates_comp_created_desc ON public.message_templates (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_overtime_records_comp_created_desc ON public.overtime_records (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_adjustments_comp_created_desc ON public.payment_adjustments (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payroll_items_comp_created_desc ON public.payroll_items (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payroll_periods_comp_created_desc ON public.payroll_periods (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payroll_periods_comp_status ON public.payroll_periods (company_id, status);
CREATE INDEX IF NOT EXISTS idx_platform_background_jobs_comp_created_desc ON public.platform_background_jobs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_background_jobs_comp_status ON public.platform_background_jobs (company_id, status);
CREATE INDEX IF NOT EXISTS idx_platform_notifications_comp_created_desc ON public.platform_notifications (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_support_sessions_comp_created_desc ON public.platform_support_sessions (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_support_sessions_comp_status ON public.platform_support_sessions (company_id, status);
CREATE INDEX IF NOT EXISTS idx_platform_system_health_events_comp_created_desc ON public.platform_system_health_events (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_tenant_exports_comp_created_desc ON public.platform_tenant_exports (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_tenant_exports_comp_status ON public.platform_tenant_exports (company_id, status);
CREATE INDEX IF NOT EXISTS idx_platform_tenant_feature_flags_comp_created_desc ON public.platform_tenant_feature_flags (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_price_list_items_comp_created_desc ON public.price_list_items (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_price_lists_comp_created_desc ON public.price_lists (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_price_overrides_comp_created_desc ON public.price_overrides (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pricing_rules_comp_created_desc ON public.pricing_rules (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_printing_methods_comp_created_desc ON public.printing_methods (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_categories_comp_created_desc ON public.product_categories (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_formulas_comp_created_desc ON public.product_formulas (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_price_history_comp_created_desc ON public.product_price_history (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_supplier_prices_comp_created_desc ON public.product_supplier_prices (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_variants_comp_created_desc ON public.product_variants (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_production_jobs_comp_created_desc ON public.production_jobs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_production_problem_reports_comp_created_desc ON public.production_problem_reports (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_production_task_material_requirements_comp_created_desc ON public.production_task_material_requirements (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_comp_created_desc ON public.purchase_orders (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_comp_created_desc ON public.purchase_requests (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_roles_comp_created_desc ON public.roles (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_saas_subscription_invoices_comp_created_desc ON public.saas_subscription_invoices (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_saas_subscription_invoices_comp_status ON public.saas_subscription_invoices (company_id, status);
CREATE INDEX IF NOT EXISTS idx_salary_advances_comp_created_desc ON public.salary_advances (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_salary_payments_comp_created_desc ON public.salary_payments (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shifts_comp_created_desc ON public.shifts (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_subscription_events_comp_created_desc ON public.subscription_events (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_items_comp_created_desc ON public.supplier_items (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_ledger_entries_comp_created_desc ON public.supplier_ledger_entries (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_material_prices_comp_created_desc ON public.supplier_material_prices (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_comp_created_desc ON public.supplier_payments (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_price_history_comp_created_desc ON public.supplier_price_history (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_returns_comp_created_desc ON public.supplier_returns (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_returns_comp_status ON public.supplier_returns (company_id, status);
CREATE INDEX IF NOT EXISTS idx_suppliers_comp_created_desc ON public.suppliers (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_attachments_comp_created_desc ON public.support_attachments (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_conversations_comp_created_desc ON public.support_conversations (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_conversations_comp_status ON public.support_conversations (company_id, status);
CREATE INDEX IF NOT EXISTS idx_support_messages_comp_created_desc ON public.support_messages (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tenant_memberships_comp_created_desc ON public.tenant_memberships (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_branch_access_comp_created_desc ON public.user_branch_access (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_permission_overrides_comp_created_desc ON public.user_permission_overrides (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_roles_comp_created_desc ON public.user_roles (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_workflow_execution_logs_comp_status ON public.workflow_execution_logs (company_id, status);
CREATE INDEX IF NOT EXISTS idx_workflow_rules_comp_created_desc ON public.workflow_rules (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_workforce_audit_logs_comp_created_desc ON public.workforce_audit_logs (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_account_transfers_branch_fk ON public.account_transfers (branch_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_branch_fk ON public.attendance_records (branch_id);
