export const ROLE_NAMES_BN: Record<string, string> = {
  business_owner: 'ব্যবসা স্বত্বাধিকারী',
  sales_manager: 'সেলস ম্যানেজার',
  designer: 'গ্রাফিক ডিজাইনার',
  production_manager: 'প্রোডাকশন ম্যানেজার',
  operator: 'মেশিন অপারেটর',
  store_manager: 'স্টোর ও ইনভেন্টরি ম্যানেজার',
  accountant: 'হিসাবরক্ষক ও বিলিং কর্মকর্তা',
  delivery_coordinator: 'ডেলিভারি ও চালান সমন্বয়ক',
  general_staff: 'সাধারণ কর্মী',
  Staff: 'সাধারণ কর্মী',
  staff: 'সাধারণ কর্মী',
  branch_manager: 'শাখা ব্যবস্থাপক',
  manager: 'ব্যবস্থাপক',
  'Business Owner': 'ব্যবসা স্বত্বাধিকারী',
  'Sales Manager': 'সেলস ম্যানেজার',
  'Graphic Designer': 'গ্রাফিক ডিজাইনার',
  'Production Manager': 'প্রোডাকশন ম্যানেজার',
  'Machine Operator': 'মেশিন অপারেটর',
  'Store & Inventory Manager': 'স্টোর ও ইনভেন্টরি ম্যানেজার',
  'Accountant & Billing Officer': 'হিসাবরক্ষক ও বিলিং কর্মকর্তা',
  'Delivery & Challan Coordinator': 'ডেলিভারি ও চালান সমন্বয়ক',
  'General Staff': 'সাধারণ কর্মী',
  'Branch Manager': 'শাখা ব্যবস্থাপক',
  'Manager': 'ব্যবস্থাপক',
}

export const ROLE_DESCRIPTIONS_BN: Record<string, string> = {
  business_owner: 'সার্বজনীন প্রশাসনিক ক্ষমতা এবং প্রাতিষ্ঠানিক পরিচালনা।',
  sales_manager: 'কোটেশন, মূল্য নির্ধারণ, গ্রাহক সম্পর্ক, ইনভয়েসিং এবং অর্ডার ব্যবস্থাপনা।',
  designer: 'আর্টওয়ার্ক প্রুফ, গ্রাহক অনুমোদন, প্রি-প্রেস যাচাই এবং ডিজাইন সংশোধন।',
  production_manager: 'কারখানা মেশিন কিউ, কাঁচামাল বরাদ্দ, কাজের ধাপ ও মান নিয়ন্ত্রণ।',
  operator: 'প্রিন্ট প্রেস পরিচালনা, ফিনিশিং কাজ, টাস্ক সম্পন্নকরণ এবং মেশিন লগ।',
  store_manager: 'কাঁচামাল রোল, কালি, বোর্ড, স্টোর লেজার এবং উপাদান প্রেরণ।',
  accountant: 'ইনভয়েসিং, রসিদ, পেমেন্ট রেকর্ডিং, ব্যাংকিং এবং আর্থিক রিপোর্ট।',
  delivery_coordinator: 'ডেলিভারি চালান, সাইট ইনস্টলেশন সাইন-অফ এবং প্রেরণের পথ।',
  general_staff: 'মৌলিক অপারেশনাল ভিউ অ্যাক্সেস সহ সাধারণ ওয়ার্কস্পেস সদস্য।',
  branch_manager: 'শাখা অপারেশন, আউটলেট সেলস, কর্মী ও শাখা সমন্বয়।',
}
